### ISSUE TITLE
Emojis Suggestion

### ISSUE THREAD

**Issue by YesYesTheDev** [get-got/discord-downloader-go#101]
I just wanted to suggest maybe you add settings for the emojis so you can save the emojis to a certain directory instead of them being saved into a emojis directory where the exe is located

**Comment by get-got** [comment]
@YesYesTheDev Reworked emojis and added support for stickers for next release. https://github.com/get-got/discord-downloader-go/commit/fc02c7501a154c7eaf23f17aa57c2239c55814b1

Dropped the emojis setting and made it settings-based. It runs upon launch after all of the other startup finishes.

```json
"emojisServers": [ "123", "456" ],
"emojisDestination": "X:/emojis", // optional, will just use subfolder "emojis" if not included. will automatically create subfolders with the server name.
"emojisFilenameFormat": "{{name}}", // optional, default is "{{ID}} {{name}}"

"stickersServers": [ "123", "456" ],
"stickersDestination": "X:/stickers", // optional, will just use subfolder "stickers" if not included. will automatically create subfolders with the server name.
"stickersFilenameFormat": "{{name}}", // optional, default is "{{ID}} {{name}}"
```
