### ISSUE TITLE
History Issue

### ISSUE THREAD

**Issue by YesYesTheDev** [get-got/discord-downloader-go#102]
When ever I do auto history or ddg history all when ever it is done doing the history it keeps closing the program when it is done

**Comment by get-got** [comment]
@YesYesTheDev Sorry for the late followup, that means it's fatally crashing. Please run within command prompt (open command prompt in that location and simply enter `discord-downloader-go.exe` and send me the error it crashed on and I can look into it.

**Comment by NimbusCloudVoid** [comment]
> discord-downloader-go.exe

![2023-09-04  WindowsTerminal_taHIYUZZh9_369](https://github.com/get-got/discord-downloader-go/assets/95382620/c43ea034-7827-4fcd-8edf-26fdd0108075)

I had this

**Comment by get-got** [comment]
> > discord-downloader-go.exe
> 
> ![2023-09-04 WindowsTerminal_taHIYUZZh9_369](https://user-images.githubusercontent.com/95382620/265533799-c43ea034-7827-4fcd-8edf-26fdd0108075.png)
> 
> I had this

@NimbusCloudVoid This will be fixed in v2.2.1, pushing now.

**Comment by YesYesTheDev** [comment]
Sorry for not responding but it is the same error that the person sent above

**Comment by get-got** [comment]
> 

@YesYesTheDev This should be fixed in the latest release, if not please let me know.

**Comment by YesYesTheDev** [comment]
I have just recently downloaded the newer version and I am getting this error

![image](https://github.com/get-got/discord-downloader-go/assets/118150960/399c60a1-a9d8-49d3-b7f2-ce3bd29d66c4)

**Comment by YesYesTheDev** [comment]
if you would like to get a faster response to me please add me a on discord ```oisj``
