### ISSUE TITLE
"Failed to convert timestamp to discord snowflake"

### ISSUE THREAD

**Issue by nabeelio** [get-got/discord-downloader-go#104]
Hi,

So I've set `autoHistory` to true, but I'm getting this error, it seems always try to download the history from the start. I try setting the date manually with `autoHistorySince`, still doesn't respect it:

```
2023/10/10 12:46:08 discord.go:98:      > Failed to convert timestamp to discord snowflake... Format: '2023-10-09', Timestamp: '2006-01-02' - Error:    %!s(<nil>)
```

**Comment by nabeelio** [comment]
> 2023/10/10 12:54:21 main.go:265:        > [History | Autorun] History Autoruns completed (for 181 channels)
2023/10/10 12:54:21 main.go:268:        > [History | Autorun] Waiting for something else to do...
2023/10/10 12:54:25 history.go:283:     ? [DEBUG | History] ***/AUTORUN: Assuming history is completed prior to 1159487294814834799

The `1159487294814834799` is a 2006 timestamp

Settings snippet:

```json
	"autoHistory": true,
	"sendAutoHistoryStatus": false,
	"sendHistoryStatus": false,
        "autoHistorySince": "2023-10-09T00:00:00Z",
```

I've tried `2023-10-09`, leaving it empty/left out

**Comment by get-got** [comment]
@nabeelio `1159487294814834799` is not a 2006 timestamp, [it's](https://snowsta.mp/?l=en-us&z=d&f=azkjrol9u3-bf3) `2023-10-05T13:48:33.316Z`.

The `2006-01-02` it shows you is the date format that Go accepts, representing YYYY-MM-DD.

Remove the timestamp portion from your setting, `T00:00:00Z`. It should just be `2023-10-09`.

The output saying "Assuming history is completed" is not related to your autoHistorySince setting. It's loading a cache file for this history channel that gets written when it runs history, meaning the cache says it has history completed up until `1159487294814834799`/`2023-10-05T13:48:33.316Z`.

**Comment by get-got** [comment]
But, the error it's giving you is nil, but it shouldn't be outputting that if it's nil, which is weird. I'll restructure that function in a coming commit and hopefully it fixes it. if you're doing 2023-10-09 it should work fine.

Either way, the bot should already be doing what you're wanting, and keeping a record of the latest messages it has 100% completion for and not going further back than that.

**Comment by nabeelio** [comment]
Ok, I see now - I'm seeing that message mainly after it's finished history for a channel

>  2023/10/11 18:05:00 history.go:552:     > [History] **/AUTORUN: Finished history for ...
2023/10/11 18:05:02 discord.go:98:      > Failed to convert timestamp to discord snowflake... Format: '2023-10-09', Timestamp: '2006-01-02' - Error:      %!s(<nil>)

**Comment by get-got** [comment]
@nabeelio Please see if v2.3.0 fixes this, let me know if not.

**Comment by nabeelio** [comment]
@get-got Looks good! Thanks!
