### ISSUE TITLE
Bot ignoring divideByUser:false and creating user directory/re-downloading anyway

### ISSUE THREAD

**Issue by kauffy** [get-got/discord-downloader-go#108]
I moved the executable to another location and changed only the destination directory in `settings.json`. I moved all the previous content that the bot had downloaded into that folder.

I have `divideByUser` set to false in the defaults and in each channel's settings.

When I run it now, it will begin downloading the history of channels it has already downloaded, and deposit the content in a folder named for the bot alongside the images folder it is supposed to be downloading to.

I have been running this as a real bot on the old machine as well as the new.

**Comment by get-got** [comment]
@kauffy Can you show the config excluding sensitive info?

**Comment by get-got** [comment]
Please try the latest version and see the changelogs. I replaced the divideBy_____ settings with subfolders.
