### ISSUE TITLE
"autoHistorySince": "2023-08-30" not acceptable format?

### ISSUE THREAD

**Issue by kauffy** [get-got/discord-downloader-go#109]
Forgive me if this is user error, but it appeared that this format `YYYY-MM-DD` was the correct one to use for `autoHistorySince`, but it looks like the bot chokes on the value and ignores it.

If it's not a bug, then it should be clearer in the documentation, so simple folk like myself know what to do.

**Comment by get-got** [comment]
You're using it correctly, you aren't the only one to have issues with it. I restructured it for the next version, hopefully it doesn't get stuck anymore.
