### ISSUE TITLE
Bot gets stuck in error loop if computer goes to sleep

### ISSUE THREAD

**Issue by nmills3** [get-got/discord-downloader-go#11]
If a computer running the downloader goes into sleep mode for a while and is then woken up the bot just logs this message every few seconds

`2021/01/27 11:04:22.684872 logging.go:63: [DG0] wsapi.go:302:heartbeat() error sending heartbeat to gateway wss://gateway.discord.gg/?v=6&encoding=json, websocket: close sent
`

this issue also effects a docker container if it is paused and then unpaused after a while. Easiest way to replicate is to start the bot in a container, pause it, wait 10 minutes and unpause the container

**Comment by get-got** [comment]
Tried to find a workaround for this but no luck yet. Discordgo doesn't seem to like when this happens, I can't get it to properly reconnect after experiencing this but keep trying.

**Comment by get-got** [comment]
This seems to work, give it a try and let me know (Docker should autobuild). https://github.com/get-got/discord-downloader-go/commit/2b01e82b906aab9e5e94ca558349e9390819291f

**Comment by nmills3** [comment]
Doesn't seem to have worked. it did say it logged in again but the error message continued and the bot wouldn't respond to commands. Here's my log [](https://pastebin.com/uxQ4hXpW)

**Comment by get-got** [comment]
Hmm, I just tested again and it reconnected fine for me after 30 minutes down. Not sure what a good universal solution would be.

**Comment by nmills3** [comment]
In fairness in the case of a docker container there isn't really any reason to pause it for an extended amount of time anyway. it was more of a windows going to sleep/vm getting paused issue
