### ISSUE TITLE
Discord downloader does not download embedded videos.

### ISSUE THREAD

**Issue by banana-man10** [get-got/discord-downloader-go#113]

**Comment by get-got** [comment]
I'll need examples to test with. It should be fetching embedded content, unless maybe that's a user account limitation.

**Comment by NimbusCloudVoid** [comment]
Try to put `"savePossibleDuplicates": true,` 

Idk why but there was some embedded videos that was still working but the bot returned 403 forbidden and when i put this setting on true, it downloaded the embedded fixing my problem.
