### ISSUE TITLE
History Since setting in .json is still ignored-- all history sought

### ISSUE THREAD

**Issue by kauffy** [get-got/discord-downloader-go#117]
This is a variation on my prior issue asking about the date format. Then I saw this issue:

[https://github.com/get-got/discord-downloader-go/issues/116#issue-2022103346](History --since not working #116)

That describes the problem exactly, except that issue was resolved by 2.4.0, and I am using 2.4.0, and still having the issue

**Comment by get-got** [comment]
I'll work on fixing this when I have time this week, in the meantime deleting the `cache/history` folder before running history should fix the issue.

**Comment by kauffy** [comment]
I've cleared cache/history, and I'm in a largely improved state, except (my autoHistorySince is set to 2023-10-31)--
![image](https://github.com/get-got/discord-downloader-go/assets/2880436/15524389-1bfd-4379-9211-f9580e60bf54)

and also
![image](https://github.com/get-got/discord-downloader-go/assets/2880436/8233e088-5364-492f-8ce1-808c35b6bd47)

**Comment by kauffy** [comment]
I guess there's an argument to be made that autoHistory should mark where the last time it downloaded from a given server/channel/format before and not search before that.

In my use case, I'm using it to grab my Midjourney images-- but I only need the history to catch whatever images I may have generated while DDG wasn't running. Of course, initially, the "grab everything" was required and worked perfectly. So many pictures!

**Comment by get-got** [comment]
_"autoHistory should mark where the last time it downloaded from a given server/channel/format before and not search before"_ is the intended purpose of `cache/history`, not only for autoHistory but for everything, but something is clearly broken. I'll need to restructure how the caching & `since` handling works.

**Comment by kauffy** [comment]
I get a lot of that output-- but a lot less of the garbage since I dumped the cache/history. And I should say that this utility is a freaking godsend. I am a packrat, and don't want to lose a single image, and given that Midjourney likes to give me images in ephemeral messages, and that their own download facility is garbage, this is-- again-- a godsend.

**Comment by get-got** [comment]
Should be fixed with v2.5.0, reopen if not.
