### ISSUE TITLE
History don't work with midjourney

### ISSUE THREAD

**Issue by Nafi7393** [get-got/discord-downloader-go#119]
I tried to ddg history then my channel ID. it scans and says i have this many messages. but the download is zero. I don't know if I am doing it anything wrong but the main thing is, the bot doesn't working while i try to download images from a channel, and that channel is have like only 250 images.

**Comment by kauffy** [comment]
Does the bot belong to the channel? Does the bot have the appropriate permissions set up? Are the "history" settings set correctly in your settings.json?

**Comment by get-got** [comment]
Please send your settings with sensitive data removed.

And what type of images are these? Direct discord attachments, direct media links, or embedded from a link?
