### ISSUE TITLE
How do i prevent the bot from stopping from running when it hasn't detected any new messages?

### ISSUE THREAD

**Issue by ea2399** [get-got/discord-downloader-go#121]

**Comment by kauffy** [comment]
Can you clarify what you mean here?

I've been using this for ~6 months, but what you've written doesn't mean anything to me.

What is it doing now? Are you using the latest version? Is your settings.json set up correctly? Does "stopping" mean it closes, or it just stops?

Some more details might help.

**Comment by get-got** [comment]
The bot doesn't stop running. It will stay alive until you interrupt it or it crashes. I'll need more info to be able to help resolve.
