### ISSUE TITLE
Support for Distillery? (Another AI Image Gen that uses Discord)

### ISSUE THREAD

**Issue by kauffy** [get-got/discord-downloader-go#127]
The title says it all. It's nowhere near as good as Midjourney, but it's something else, and they set it up in Discord the same way.

**Comment by kauffy** [comment]
Actually, I take it back. It would only work using their bot in Direct Messages-- you can't (as far as I know) add their bot to your own server.

**Comment by get-got** [comment]
What aspect doesn't currently work for downloading from Distillery? From googling it just looks like it sends as standard Discord attachments, and you can use the prior discussed message content logging feature to save the prompt (pushing update today).

**Comment by kauffy** [comment]
Wouldn't the bot need to be on their server? Like, have permissions to it? (Assuming no self-bot)

**Comment by kauffy** [comment]
Yeah, that's what I thought-- I guess, in that case, it would work! I was thinking with using my current bot. Although I think Distillery is "open"-- in theory, the bot could join the Discord on its own, couldn't it?

**Comment by get-got** [comment]
Even if it's a public server, only someone with the core Administrator permission can add genuine bots.
