### ISSUE TITLE
"x509: certificate signed by unknown authority" when bot encounters a funimation url

### ISSUE THREAD

**Issue by nmills3** [get-got/discord-downloader-go#13]
Someone in my server posted this link [https://www.funimation.com/shows/fatestay-night-unlimited-blade-works/](https://www.funimation.com/shows/fatestay-night-unlimited-blade-works/) and the bot responded with this message

`Download Failure
Gave up trying to download
https://www.funimation.com/shows/fatestay-night-unlimited-blade-works/
after 3 failed attempts...

Download Failed - Error Downloading URL Response
ERROR: Get "https://www.funimation.com/shows/fatestay-night-unlimited-blade-works/": x509: certificate signed by unknown authority

discord-downloader-go v1.4.2-a — discordgo v0.22.0`

I'm running the bot in a docker container and it only seems to have this issue with funimation links

**Comment by get-got** [comment]
@nmills3 Can confirm this is a Docker-specific issue. No issues when running on Windows but I encountered the same error in a Docker container.

**Comment by nmills3** [comment]
It would be possible to manually add the missing certificates but that doens't seem like a good long term solution

**Comment by get-got** [comment]
@nmills3 Not sure what changed but this seems to be fine now in docker containers.
