### ISSUE TITLE
2.5.1 - Emoji/Sticker Configuration blank - blank config stops channel processing (?)

### ISSUE THREAD

**Issue by kauffy** [get-got/discord-downloader-go#132]
This is in my config.json.

![image](https://github.com/get-got/discord-downloader-go/assets/2880436/55a866e5-10ad-475b-a6a2-fa0878783644)

Then I get a message like this, and nothing is downloaded from the sidesketch channel.
![image](https://github.com/get-got/discord-downloader-go/assets/2880436/27e096ef-9617-49d3-9d45-13df44e5e3b3)

I've never had these values set before, but also never had this issue before.

**Comment by kauffy** [comment]
I'm also unclear how the emoji/sticker stuff is supposed to be configured. In theory, whatever it downloads for this, would go to the same place as the other things in the channel, so it would follow the same rules, as opposed to being stored separately, as the settings seem to indicate.

**Comment by kauffy** [comment]
I filled in the same directory as the other destination, and now it does not complain. However, it is still not downloading from the #sidesketch channel. And, depending where they're supposed to be, I do not see anything that looks like an emoji or sticker download-- but I'm also not sure what they're supposed to be.

**Comment by get-got** [comment]
You can't have the server lists be blank like that. These settings only exist globally, not inside of sources, and the lists should be server IDs to download from, i.e. `"emojisServers": [ "12343555533344", "232113233233232", "343343434343434" ],` and the destination should be a specific location to download these, same as the sources, but it also can't be blank.

> _"In theory, whatever it downloads for this, would go to the same place as the other things in the channel, so it would follow the same rules, as opposed to being stored separately, as the settings seem to indicate."_

No, emoji/sticker downloading is entirely separate from source downloading. It doesn't coincide with those configs whatsoever, the server IDs for emojis/stickers must be specified in the lists and an appropriate download directory must be specified. No correlation with the source download setups at all.

**Comment by kauffy** [comment]
So it's just downloading the collection of emoji/stickers for the listed servers?

Anyway, without changing anything (servers still blank) it does not complain about those destination directories, nor the missing servers. _And_ I don't know what the holdup was, but it did eventually process the rest of that channel.
