### ISSUE TITLE
Personal Downloader Example

### ISSUE THREAD

**Issue by shadybrady101** [get-got/discord-downloader-go#142]
I keep trying to use the personal self bot example and I always get an error, I'm trying to get two channels to download to separate folders.

**Comment by get-got** [comment]
Can you show the error you're getting as well as your config with login/sensitive info removed?

**Comment by shadybrady101** [comment]
![image_2024-04-28_121628653](https://github.com/get-got/discord-downloader-go/assets/69660019/5fd9e322-8743-4bc0-833e-abf18cea7adc)
{
    "_constants": null,
    "credentials": {
        "token": "__token",
        "flickrApiKey": "__flickr_api_key"
    },
    "admins": [ "__USER_ME" ],
    "adminChannels": [
        {
            "channel": "__CHANNEL_P_DDG_UBADMIN"
        }
    ],
    "overwriteTwitterPath": "/home/bots/shared/twitter_cookies.json",
    "overwriteInstagramPath": "/home/bots/shared/instagram_cookies.json",
    "debug": true,
    "allowSkipping": true,
    "scanOwnMessages": false,
    "autoHistory": true,
    "githubUpdateChecking": false,
    "presenceEnabled": false,
    "exitOnBadConnection": false,
    "presenceStatus": "invisible",
    "channels": [
        {
            "channels": [
                "__CHANNEL_MEMESERVER1_MEMES",
                "__CHANNEL_MEMESERVER2_MEMES",
                "__CHANNEL_MEMESERVER3_SHITPOSTING",
                "__CHANNEL_MEMESERVER4_MEMES"
             ],
            "destination": "/var/www/html/files/ddg/memes",
            "enabled": true,
            "allowCommands": false,
            "sendErrorMessages": false,
            "scanEdits": true,

            "presenceEnabled": false,
            "reactWhenDownloaded": false,

            "subfolders": [
                "{{serverName}}"
            ],
        },
        {
            "channels": [
                "__CHANNEL_MEMESERVER2_NSFW_MEMES",
                "__CHANNEL_MEMESERVER4_NSFW_MEMES"
             ],
            "destination": "/var/www/html/files/ddg/nsfw",
            "enabled": true,
            "allowCommands": false,
            "sendErrorMessages": false,
            "scanEdits": true,

            "presenceEnabled": false,
            "reactWhenDownloaded": false,

            "subfolders": [
                "{{serverName}}"
            ],
        }
    ]
}

**Comment by get-got** [comment]
You have some trailing commas, those cause errors in json. The last object in a group can't have a comma. I think it's just your subfolder objects:

![image](https://github.com/get-got/discord-downloader-go/assets/43052079/99f02d08-dc59-4dff-9b74-fea97a390a16)

**Comment by shadybrady101** [comment]
Thank you, of course its a comma, I got it from the example, it might be good to fix that.

**Comment by get-got** [comment]
Fixed it thanks, didn't realize you meant that section, I must have left that when I stripped my other settings out.
