### ISSUE TITLE
ddg history not downloading midjourney images on my server.

### ISSUE THREAD

**Issue by tamal777** [get-got/discord-downloader-go#143]
after processing no files has been downloaded.

**Comment by get-got** [comment]
Do you have ignoreBots set to false? It's true by default.

**Comment by tamal777** [comment]
> Do you have ignoreBots set to false? It's true by default.

I have set it to false and still does not work.

**Comment by kauffy** [comment]
This may be due to ephemeral messages from Discord. I'll make a separate issue about it.
