### ISSUE TITLE
Bots Crashing With Multiple Instances

### ISSUE THREAD

**Issue by BigFlubba** [get-got/discord-downloader-go#145]
I am using all real bots and they are all sharing the same cache, database, and log directories. I am running 10 instances at once each in charge of 5 channels each on a different server. Each has their on config files. They are all crashing at once and last i looked at the logs they crashed while all of them doing an auto history run. The last interesting message I got on one of the bots was this then everything crashed. none of the rest of them had anything out of the ordinary.

```
2024/06/13 14:01:53 history.go:427:     > [96m[History][0m [31m978799777997262918/AUTORUN: Tried to edit status message but it doesn't exist, sending new one.[0m
```

After relaunching any bot after they all crash I have to manually delete the database for them to work again. They seem to crash randomly and one may survive, but also none of them will. I also tested it with jut one instance running and it ran with no issues for 3 hours and it got over 500 messages downloaded.

**Comment by get-got** [comment]
This is the same issue as here: https://github.com/get-got/discord-downloader-go/issues/144

There is currently no fix.
