### ISSUE TITLE
All links broken with new Discord update

### ISSUE THREAD

**Issue by BigFlubba** [get-got/discord-downloader-go#148]
Unfortunately with the new update from Discord, they changed how links are formatted. Instead of it being simple they wanted to make it stupid and complex and add garbage to the end of the link (I'm assuming tracking data). The bot is broken until the new links are supported. All you get is a 404 error. This only applies to attachments, but knowing discord that may change.

Before update:
https://cdn.discordapp.com/attachments/1047689306690555904/1074531708524834867/image.png

After update:
https://cdn.discordapp.com/attachments/1047689306690555904/1074531708524834867/image.png?ex=6697e263&is=669690e3&hm=102c8e2f1bb646fe2e595d4d4458bb1cf9a7c259979c6a6a3aff0e49ddf2a70a&

**Comment by get-got** [comment]
I don't think this breaks anything and any issues with this were likely isolated. Some time back I fixed this issue, and testing with my own genuine bot and selfbot, discord links seem to currently work fine.
