### ISSUE TITLE
go runtime error

### ISSUE THREAD

**Issue by DoyunShin** [get-got/discord-downloader-go#18]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x1421d10]

goroutine 43 [running]:
main.handleMessage(0xc000460580, 0x0, 0x0)
        /home/travis/gopath/src/github.com/get-got/discord-downloader-go/handlers.go:47 +0xd0
main.messageCreate(0xc000128240, 0xc000006b10)
        /home/travis/gopath/src/github.com/get-got/discord-downloader-go/handlers.go:31 +0x3c
github.com/bwmarrin/discordgo.messageCreateEventHandler.Handle(0x1614da0, 0xc000128240, 0x14fd780, 0xc000006b10)
        /home/travis/gopath/pkg/mod/github.com/bwmarrin/discordgo@v0.22.0/eventhandlers.go:497 +0x52
created by github.com/bwmarrin/discordgo.(*Session).handle
        /home/travis/gopath/pkg/mod/github.com/bwmarrin/discordgo@v0.22.0/event.go:171 +0x118

**Comment by DoyunShin** [comment]
Running on the windows 10 20H2

**Comment by get-got** [comment]
Can you post your settings.json (with sensitive info removed of course) so I can try and recreate it to see which part is getting that error?

If you don't want to post publicly, join the discord in the readme and dm me it.

**Comment by DoyunShin** [comment]
oh now i found the error, my settings.json had problem. After i recreate the settings.json, it worked.

i wrote like thisone

"channels": {"server": "00000000000000" ~~

**Comment by DoyunShin** [comment]
`{
	"credentials": {
		"token": "token"
	},
	"admins": [
		"4266708293598576**",
		"8211643166182605**",
		"2592553754869104**"
	],
	"adminChannels": [
		{
			"channel": "8412930402115911**"
		}
	],
	"debugOutput": true,
	"commandPrefix": "qk!",
	"allowSkipping": true,
	"scanOwnMessages": false,
	"githubUpdateChecking": true,
	"presenceEnabled": true,
	"presenceStatus": "dnd",
    "presenceType": 3,
    "presenceOverwrite": "{{count}} files",
	"servers": null,
	"embedColor": "#FFABCD",
	"channels": [
		{
			"server": "83809079823446****",
			"destination": "Z:/[0FF27C] Download/",
			"enabled": true,
			"allowCommands": true,
			"errorMessages": true,
			"scanEdits": true,
			"ignoreBots": false,
			"updatePresence": true,
			"reactWhenDownloaded": false,
			"reactWhenDownloadedEmoji": "",
			"blacklistReactEmojis": [],
			"typeWhileProcessing": false,
			"usersAllWhitelisted": true,
			"divideFoldersByServer": true,
			"divideFoldersByChannel": true,
			"divideFoldersByUser": true,
			"divideFoldersByType": false,
			"saveImages": true,
			"saveVideos": true,
			"saveAudioFiles": true,
			"saveTextFiles": true,
			"saveOtherFiles": true,
			"savePossibleDuplicates": true,
			"extensionBlacklist": [
				".htm",
				".html",
				".php",
				".exe",
				".dll",
				".bin",
				".cmd",
				".sh"
			]
		}
	]
}`
