### ISSUE TITLE
Checkmarks

### ISSUE THREAD

**Issue by Karter-Key** [get-got/discord-downloader-go#20]

**Comment by Karter-Key** [comment]
Woops, sent it without text.
That aside, I seem to have an issue with the images that get downloaded automatically having a checkmark emote reaction under it. Don't think I set it to do that at least, unless it's supposed to always do that (if that's the case, there a way to make it no stop?). 
To give some context, I came from Seklfreak which I had been using for long time, and imported the config.ini. At a glance by opening the settings.json created from it, I don't see anything that would say it'd apply those checkmarks emotes. Is there something I need to remove or add? Any help to clear thing up would be appreciated.

**Comment by get-got** [comment]
Add ``"reactWhenDownloaded": false,`` to each channels config where you don't want it to react

**Comment by Karter-Key** [comment]
Thanks, working as I've hoped!
