### ISSUE TITLE
Downloader crash on using ddg history

### ISSUE THREAD

**Issue by BL4D35M1TH** [get-got/discord-downloader-go#21]
I run this application as root. All features worked fine before the latest release.

Steps to reproduce:
type `ddg history` in the monitored channel

error log:
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0xa83cdd]

goroutine 80 [running]:
main.isLocalAdmin(0xc000139a20, 0x11)
	/home/travis/gopath/src/github.com/get-got/discord-downloader-go/discord.go:283 +0x19d
main.handleCommands.func6(0xc00007a320)
	/home/travis/gopath/src/github.com/get-got/discord-downloader-go/commands.go:256 +0x1c9a
github.com/Necroforger/dgrouter/exrouter.WrapHandler.func1(0xbcf4e0, 0xc00007a320)
	/home/travis/gopath/pkg/mod/github.com/!necroforger/dgrouter@v0.0.0-20200517224846-e66453b957c1/exrouter/router_wrapper.go:128 +0x42
github.com/Necroforger/dgrouter/exrouter.(*Route).FindAndExecute(0xc00050e508, 0xc000f52240, 0xc0002be8f8, 0x4, 0xc00050b2c0, 0x12, 0xc000139a20, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/github.com/!necroforger/dgrouter@v0.0.0-20200517224846-e66453b957c1/exrouter/router_wrapper.go:114 +0x622
main.handleMessage(0xc000fc7b80, 0x0, 0x0)
	/home/travis/gopath/src/github.com/get-got/discord-downloader-go/handlers.go:67 +0x104e
main.messageCreate(0xc000f52240, 0xc00050e8b0)
	/home/travis/gopath/src/github.com/get-got/discord-downloader-go/handlers.go:31 +0x35
github.com/bwmarrin/discordgo.messageCreateEventHandler.Handle(0xc851f8, 0xc000f52240, 0xb6d620, 0xc00050e8b0)
	/home/travis/gopath/pkg/mod/github.com/bwmarrin/discordgo@v0.22.0/eventhandlers.go:497 +0x4b
created by github.com/bwmarrin/discordgo.(*Session).handle
	/home/travis/gopath/pkg/mod/github.com/bwmarrin/discordgo@v0.22.0/event.go:171 +0x111`

**Comment by get-got** [comment]
Try compiling the latest commit ( https://github.com/get-got/discord-downloader-go/commit/f8bcf41f4b7d1e3924107408d520fa8edcb22937 ) or tell me which platform you're on and I'll build it for you. Added nil/error checks to that function you crashed on, and logging for why it may crash if you have debugOutput enabled.

**Comment by BL4D35M1TH** [comment]
> Try compiling the latest commit ( [7699029](https://github.com/get-got/discord-downloader-go/commit/7699029ab6bd4c4e2fa12894ff55742bc03ea921) + [f8bcf41](https://github.com/get-got/discord-downloader-go/commit/f8bcf41f4b7d1e3924107408d520fa8edcb22937) ) or tell me which platform you're on and I'll build it for you. Added nil/error checks to that function you crashed on, and logging for why it may crash if you have debugOutput enabled.

The latest release fixed the issue. Thanks!
