### ISSUE TITLE
Bot randomly reacts to messages with emojis

### ISSUE THREAD

**Issue by BRN-00** [get-got/discord-downloader-go#25]
so the bot just started to react to messages with emojis and got me banned because the server thought that i was trolling.
i dont know if this can be disabled or what but i think its a problem.

i didnt had that problem before. i downloaded the newest version and ran for 3-4 hours with no porblem.
and when i started again this morning its started to react to messages.i dont know why. everything is the same in the setting
maybe its only for me but if not, i think it should be fixed

**Comment by get-got** [comment]
@BRN-00 Please make sure you have `"reactWhenDownloaded"` set to `false` for that channel(s) configuration. It is true by default if that variable is missing.

**Comment by BRN-00** [comment]
oh.well i cant because i have the barebone version. is there any way to make it selfbot version. or i have to paste that part it in?

thank you for the quick answer

**Comment by get-got** [comment]
@BRN-00 Just add `"reactWhenDownloaded": false,` to the channel config or `all` config. It depends what you're using. If you need help, paste or screenshot your config.

**Comment by BRN-00** [comment]
to this part right for all
![image](https://user-images.githubusercontent.com/82290486/123481139-9d770100-d603-11eb-8d5e-019748647108.png)

**Comment by get-got** [comment]
@BRN-00 No it goes within the `channels` entries.

```json
    "channels": [
        {
            "channel": "aaaaaaaaaaaaaaa",
            "destination": "aaaaaaaaaaaaaaaaaa",
            "reactWhenDownloaded": false
        },
    ]
```

**Comment by BRN-00** [comment]
ok ,thank you
