### ISSUE TITLE
Is it possible to organize images and messages per user into their own folders?

### ISSUE THREAD

**Issue by millysecurity** [get-got/discord-downloader-go#27]
I am only logging one channel in my server. The messages are being sent to one destination and being sorted by user. Is it possible to make it so the every message and image sent by a user is organized into their own folder?

**Comment by get-got** [comment]
@millysecurity I'm confused by what you mean, you can use

`"divideFoldersByUser" ( settings.channels[].divideFoldersByUser : boolean )`

to separate downloaded content by users, is that what you're looking for?
