### ISSUE TITLE
Won't download from specific channel/server

### ISSUE THREAD

**Issue by AnonymouseCow** [get-got/discord-downloader-go#29]
So the downloader works great, but only for some servers, I have a server where images are constantly being posted and no matter what the bot won't detect or save the images.. I have the channel in settings and have even tried adding the entire server but it didn't work. I have attached the settings.
(I dont know why it appears deformed.)
`     
"servers": [
        {
            "server": "270613445177638922",
            "destination": "/home/awildfrog/Share/memeverity/",
            "divideFoldersByChannel": true
        }
    ],
    "channels": [
        {
            "channel": "680928395399266314",
            "destination": "/home/awildfrog/Share/memeverity/",
            "overwriteAllowSkipping": false,
            "saveImages": true,
            "saveVideos": true,
            "saveAudioFiles": true,
            "saveTextFiles": false,
            "saveOtherFiles": false
        },
`

**Comment by get-got** [comment]
Does the bot seem to handle the messages at all? Or does it act like it can't even see them?

If you build from the source yourself, I added a thing that validates channels/servers upon login to know if there's any problems. May not make much difference but may be worth a chance. I'm away from home for another week but if you're still having that problem, leave the issue open and I'll help when I'm back.

**Comment by AnonymouseCow** [comment]
The bot doesn't handle the messages or see them at all, its like i never even added the channel. I'll try what you said.

**Comment by AnonymouseCow** [comment]
So the bot does the exact same thing although it spams the output with this:
`2021/07/10 16:15:28 main.go:345: Settings reloaded, bound to 5 channel(s) and 1 server(s)                                                               
2021/07/10 16:15:35 logging.go:63: [DG1] wsapi.go:586:onEvent() unknown event: Op: 0, Seq: 106, Type: CHANNEL_UNREAD_UPDATE, Data: {"guild_id":"150074202727251969","channel_unread_updates":[{"last_message_id":"863501363610779658","id":"820592312236245014"},{"last_message_id":"863511067007123486","id":"779975211063443456"},{"last_message_id":"863442055589527553","id":"842346390256746506"},{"last_message_id":"863513788569747467","id":"849365974016720966"},{"last_message_id":"863513479965311006","id":"150075910341525504"},{"last_message_id":"863507150897676318","id":"850830105256394782"},{"last_message_id":"860034619248082994","id":"724970895105327134"},{"last_message_id":"863003342303920153","id":"818999967045386260"},{"last_message_id":"863508469049720882","id":"366640786181455883"},{"last_message_id":"636993906931793921","id":"580324954386464768"},{"last_message_id":"863508978167840808","id":"366629978101514241"},{"last_message_id":"863510338287435776","id":"851511627727503411"},{"last_message_id":"863500805029101588","id":"744960550147981424"},{"last_message_id":"863501413135679528","id":"597057732163665920"},{"last_message_id":"863116771267444756","id":"762373907168362506"},{"last_message_id":"863513768096563280","id":"150078338839347201"},{"last_message_id":"863498140303622164","id":"744935060784021595"},{"last_message_id":"863499965480042517","id":"733292992793804910"},{"last_message_id":"854933240724062208","id":"802910951015841792"},{"last_message_id":"863513693060464720","id":"785821764839669791"},{"last_message_id":"863497396389806081","id":"701208444996288552"},{"last_message_id":"863511357562683443","id":"366624841798778890"},{"last_message_id":"843308017336057897","id":"782510515133349888"},{"last_message_id":"863467821065699358","id":"361255951514206208"},{"last_message_id":"863169861865963591","id":"437651858253676555"},{"last_message_id":"862278472923349013","id":"552610227363643412"},{"last_message_id":"743242859028807752","id":"731691901677207602"},{"last_message_id":"863512463349252127","id":"650905362454806539"},{"last_message_id":"863513740657688627","id":"857038530467332106"},{"last_message_id":"863513786500513793","id":"366624876544655360"},{"last_message_id":"863513788199075870","id":"546528119281156106"},{"last_message_id":"863466527600017468","id":"612585465911967754"},{"last_message_id":"863494787813605376","id":"224004427583848449"},{"last_message_id":"863507540716552223","id":"744934218387292200"},{"last_message_id":"854134358482354186","id":"592584077257736192"},{"last_message_id":"863365831189332009","id":"459415849632268298"},{"last_message_id":"863500201365078036","id":"769236738894856202"},{"last_message_id":"863513358157611009","id":"548724216292311070"},{"last_message_id":"863513732620484622","id":"366624802024325120"},{"last_message_id":"863513797284855819","id":"406999049619898378"},{"last_message_id":"863513800799813662","id":"150074202727251969"},{"last_message_id":"863508300241567745","id":"733293065237692425"},{"last_message_id":"849209117947723776","id":"844501182092410900"},{"last_message_id":"863496303052980224","id":"730269030023299092"},{"last_message_id":"817233418731257856","id":"814370412845989888"},{"last_message_id":"863508510385635379","id":"844847340519030784"},{"last_message_id":"863508097120600085","id":"585926993174855683"},{"last_message_id":"858642657701396511","id":"792744505379127296"},{"last_message_id":"863506290038538291","id":"818013673892741130"},{"last_message_id":"860201867522211870","id":"648261993937240064"},{"last_message_id":"855984905271771157","id":"790297914861289512"},{"last_message_id":"863508977500160030","id":"150250250471342080"},{"last_message_id":"808080137677307954","id":"724971526201409587"},{"last_message_id":"360301972965818371","id":"353318556857008129"},{"last_message_id":"595171990449684480","id":"452837910409117698"},{"last_message_id":"797389507636232202","id":"797291270032588880"},{"last_message_id":"853434097475911690","id":"852319672539152404"},{"last_message_id":"863384480542228490","id":"765026700865306684"},{"last_message_id":"863497319014203422","id":"592580861543841802"},{"last_message_id":"863410699001659394","id":"333731806509531147"},{"last_message_id":"863512202152640552","id":"744934684324266125"},{"last_message_id":"863498850715303986","id":"733293013169602590"},{"last_message_id":"863493336061313024","id":"150255535927721984"},{"last_message_id":"863513781824520223","id":"579766813622272016"},{"last_message_id":"766872835754295306","id":"763291284868694036"},{"last_message_id":"863506582393323570","id":"150077608602632192"},{"last_message_id":"861131181495943188","id":"855957242020626432"},{"last_message_id":"863507446357033010","id":"765326574496645220"},{"last_message_id":"863508428579274792","id":"582161770597056523"},{"last_message_id":"862188248297635860","id":"381544118968647680"},{"last_message_id":"863507123512934421","id":"744933772629377175"},{"last_message_id":"863512610803941376","id":"733292969712549998"},{"last_message_id":"863508599565451265","id":"744934011704705212"},{"last_message_id":"863513798072467497","id":"360318833644535808"},{"last_message_id":"851102021196578837","id":"839670119033995305"},{"last_message_id":"863120989419733043","id":"638801749498658826"},{"last_message_id":"862909928531951636","id":"541943032791040013"},{"last_message_id":"797603304355921932","id":"701702989785858118"},{"last_message_id":"854933151578062848","id":"801557724503736335"},{"last_message_id":"858377330807144464","id":"796965664983482418"},{"last_message_id":"861130786669068299","id":"765061758737055764"},{"last_message_id":"822715074917302312","id":"565952645387386910"},{"last_message_id":"863513038363295744","id":"150078388932050945"},{"last_message_id":"846465336702533642","id":"844501814987456552"},{"last_message_id":"861834302027333653","id":"678671353473269799"},{"last_message_id":"863513739277500417","id":"198120770314960896"},{"last_message_id":"863513787646214174","id":"366624514651717663"},{"last_message_id":"863506310586302474","id":"815449278159126528"},{"last_message_id":"846130670573322320","id":"832396209057693746"},{"last_message_id":"862186180636311552","id":"763949648757915663"},{"last_message_id":"832031562601857044","id":"721916692241842266"},{"last_message_id":"863381931386470430","id":"678849276402466849"},{"last_message_id":"863426332486926356","id":"537027793322639363"},{"last_message_id":"850433120242892854","id":"588895527026819073"},{"last_message_id":"863490536491843614","id":"810050718769479720"},{"last_message_id":"863512127251284041","id":"744935954992594974"},{"last_message_id":"862781702655967232","id":"612135405197852682"}]}
2021/07/10 16:15:55 logging.go:63: [DG1] wsapi.go:586:onEvent() unknown event: Op: 0, Seq: 127, Type: CHANNEL_UNREAD_UPDATE, Data: {"guild_id":"270613445177638922","channel_unread_updates":[{"last_message_id":"673573122422865970","id":"546744435375865867"},{"last_message_id":"816576401113219093","id":"744005205581889536"},{"last_message_id":"496462235477213185","id":"486139558489096192"},{"last_message_id":"863291743377031172","id":"793283928051286037"},{"last_message_id":"655424404813250580","id":"613451181414547456"},{"last_message_id":"719209646233223199","id":"682755975828078614"},{"last_message_id":"863496824747720706","id":"526552308017004544"},{"last_message_id":"717392072075903076","id":"713523875513630740"},{"last_message_id":"857681142949740584","id":"612053718246096906"},{"last_message_id":"863170616517460008","id":"681947053189758984"},{"last_message_id":"797302875348664380","id":"755414022483869716"},{"last_message_id":"863424326987677716","id":"578608997922373636"},{"last_message_id":"682294569391620204","id":"681155550137942037"},{"last_message_id":"862672614182879250","id":"493467359537922070"},{"last_message_id":"863513849864650803","id":"825433206064152596"},{"last_message_id":"553504311921999883","id":"465970516943962122"},{"last_message_id":"546747942816579605","id":"474581943652974603"},{"last_message_id":"772803433702359060","id":"680433084759539746"},{"last_message_id":"495876901135450114","id":"465916519298367488"},{"last_message_id":"863510034545508358","id":"863484961444200459"},{"last_message_id":"863510904804474890","id":"825432956968501328"},{"last_message_id":"609446218602381322","id":"594297031225507880"},{"last_message_id":"680927266045296653","id":"599736378510802966"},{"last_message_id":"825370447327395862","id":"549166897019748363"},{"last_message_id":"584302642768117770","id":"526385643455119370"},{"last_message_id":"829616245191344158","id":"713887570676678749"},{"last_message_id":"863051579375222814","id":"863051415805886464"},{"last_message_id":"812038911852675158","id":"732024840802009138"},{"last_message_id":"863511388906586132","id":"553626645765029903"},{"last_message_id":"750452678043369514","id":"660550726233358337"},{"last_message_id":"584305802433658891","id":"493811522326364219"},{"last_message_id":"863513463971512320","id":"682752960115114004"},{"last_message_id":"863499181472612352","id":"863497315826532403"},{"last_message_id":"863513879845535774","id":"680928395399266314"},{"last_message_id":"862729192554889246","id":"862513822543511592"},{"last_message_id":"862752674096480285","id":"862751221114601482"},{"last_message_id":"837338646042378280","id":"303918923596824578"},{"last_message_id":"732024007045677057","id":"680928626010750990"},{"last_message_id":"822605494258630706","id":"557611317532557315"},{"last_message_id":"586542035021070340","id":"547540548697849876"},{"last_message_id":"662477145611829248","id":"270613445177638922"},{"last_message_id":"758101115308212274","id":"744005528715526224"},{"last_message_id":"863351557407113246","id":"863350917687934976"},{"last_message_id":"539490530145337345","id":"468512890866106370"},{"last_message_id":"612289146060537856","id":"491952930543632384"},{"last_message_id":"824646331825651743","id":"662748383525470264"},{"last_message_id":"825424951614898236","id":"546736153278021662"},{"last_message_id":"863498724608311346","id":"827268432180805642"},{"last_message_id":"643475871616860190","id":"537076486750994442"},{"last_message_id":"597162222476853279","id":"596107993494454282"},{"last_message_id":"784809471087214592","id":"546689309361831936"},{"last_message_id":"765053407920128040","id":"493457183925600268"},{"last_message_id":"602258287433351172","id":"487742548228571137"},{"last_message_id":"851008178165776414","id":"848160627616645140"},{"last_message_id":"584305920075628553","id":"506093091938369546"},{"last_message_id":"613799794741084170","id":"453169698989670401"},{"last_message_id":"863513883683061780","id":"683113219392667708"},{"last_message_id":"635538106841563157","id":"564484314117570571"},{"last_message_id":"539482611651706899","id":"465641306446757893"},{"last_message_id":"863505194230480896","id":"624988134291275777"},{"last_message_id":"731576068804313178","id":"480515039795871764"},{"last_message_id":"862583214068727829","id":"862575106009858059"},{"last_message_id":"848163451724759070","id":"509155748794728454"},{"last_message_id":"863004807514292244","id":"862986505106882570"},{"last_message_id":"773591583241142314","id":"766104340464795658"},{"last_message_id":"546609890408529920","id":"422607414853107712"},{"last_message_id":"487781583873376266","id":"487396770909782017"},{"last_message_id":"863499238938640454","id":"863418048220626944"},{"last_message_id":"849724747428266004","id":"491953095501152256"},{"last_message_id":"734462797710098444","id":"708157054681874433"},{"last_message_id":"849382037537292293","id":"676972058890076189"},{"last_message_id":"863500554754981928","id":"637743642425163788"},{"last_message_id":"820022348622069761","id":"717148878029455440"},{"last_message_id":"863499196614967326","id":"863497452983025724"},{"last_message_id":"825291427633954836","id":"546736071719911434"},{"last_message_id":"680928459169857560","id":"546735865775259648"},{"last_message_id":"863438668005638174","id":"493447396425072656"},{"last_message_id":"584306106801848320","id":"465916603301625857"},{"last_message_id":"539487170688188432","id":"538490325099085858"},{"last_message_id":"848396924952379402","id":"452276275600424960"},{"last_message_id":"837338760781758464","id":"650066279222476830"},{"last_message_id":"863499467125817364","id":"860982101310046218"},{"last_message_id":"863191151477129276","id":"863174630918193152"},{"last_message_id":"863511204139368489","id":"546736601385140244"},{"last_message_id":"853654785872756737","id":"758731167322079242"},{"last_message_id":"584305691620016138","id":"471820352625049600"},{"last_message_id":"750381771819843614","id":"494264232611676181"},{"last_message_id":"584306036022837254","id":"485816725347106819"},{"last_message_id":"848238548104118273","id":"847896117726281738"},{"last_message_id":"863513758907629588","id":"422606347205476352"},{"last_message_id":"652561380695605248","id":"649387345208148013"},{"last_message_id":"613808190009770034","id":"602567271331921944"},{"last_message_id":"554452740043046913","id":"439956808191442944"},{"last_message_id":"862824503461019668","id":"862824331003559946"},{"last_message_id":"863314457367019531","id":"493457415111704577"},{"last_message_id":"584305860705255464","id":"517830904408834068"},{"last_message_id":"816578352076816424","id":"744005104881107095"},{"last_message_id":"858317979623751680","id":"272424583917862912"},{"last_message_id":"787467651575447563","id":"609337677736706058"},{"last_message_id":"846524456808873995","id":"752576331879022593"},{"last_message_id":"862750241010483262","id":"599894564245078016"},{"last_message_id":"862882107884699658","id":"862641593676595200"},{"last_message_id":"863512585117761556","id":"465656776466104321"},{"last_message_id":"863404838804783124","id":"863386730015096842"},{"last_message_id":"863509286856294410","id":"454962031607414784"},{"last_message_id":"623620163270606849","id":"491971244640567296"},{"last_message_id":"769493884840968192","id":"702700350225907772"},{"last_message_id":"863468684667912193","id":"549166968423579689"},{"last_message_id":"863499324818456592","id":"863349401124077578"}]}
`

**Comment by AnonymouseCow** [comment]
Does my account not having permission to send images to the channel have any influence on the bots ability to save things?

**Comment by get-got** [comment]
That permission shouldn't effect it. I guess just play around and if you don't have it fixed when I'm back home I can help. Will be around the 18th.

**Comment by get-got** [comment]
@AnonymouseCow Sorry for late response. If you're still having issues and want to get it working, can you send your full settings.json (with sensitive stuff removed)?

**Comment by AnonymouseCow** [comment]
okay,
 `    "adminChannels": [
        {
            "channel": "863475312200515594"
        }
    ],
    "debugOutput": false,
    "commandPrefix": "ddg",
    "scanOwnMessages": false,
    "allowSkipping": false,
    "allowGlobalCommands": true,
    "asyncHistory": false,
    "downloadRetryMax": 10,
    "downloadTimeout": 200,
    "githubUpdateChecking": true,
    "filterDuplicateImages": true,
    "filterDuplicateImagesThreshold": 75,
    "presenceEnabled": false,
    "presenceStatus": "dnd",
    "presenceType": 3,
    "presenceOverwrite": "{{count}} files",
    "filenameDateFormat": "2006.01.02-15.04.05 ",
    "embedColor": "#EE22CC",
    "inflateCount": 12345,
    "channels": [
        {
            "channels": ["824349273642500187","825938972794290177","797305330374803476"],
            "destination": "/home/******/Share/memeverity/",
            "overwriteAllowSkipping": false,
            "saveImages": true,
            "saveVideos": true,
            "reactWhenDownloaded":true,
            "saveAudioFiles": true,
            "allowCommands": false,
            "errorMessages": false,
            "saveTextFiles": true,
            "saveOtherFiles": true,
                    "filters": {
            "blockedExtensions": [
                ".htm",
                ".html",
                ".php",
                ".bat",
                ".sh",
                ".jar",
                ".exe"
            ]
        }
        },
        {
        "channels":["863475312200515594"],
        "destination": "/home/awildfrog/Share/memeverity/testchan",
    "overwriteAllowSkipping": false,
            "saveImages": true,
            "saveVideos": true,
            "reactWhenDownloaded":true,
            "saveAudioFiles": true,
            "allowCommands": false,
            "errorMessages": false,
            "saveTextFiles": true,
            "saveOtherFiles": true,
                    "filters": {
            "blockedExtensions": [
                ".htm",
                ".html",
                ".php",
                ".bat",
                ".sh",
                ".jar",
                ".exe"
            ]
            }
        },
        {
            "channels": [ "779670585936445460", "824349273642500187","680928395399266314", "406138198155198464","851575915250712666","787501644405407795","825250935001055252","761692792086593607","842038609497423872"],
        "destination": "/home/awildfrog/Share/memeverity/",
        "allowCommands": false,
        "errorMessages": false,
        "scanEdits": true,
        "ignoreBots": false,
        "overwriteAutorunHistory": false,
        "updatePresence": false,
        "typeWhileProcessing": false,
        "divideFoldersByServer": false,
        "divideFoldersByChannel": false,
        "divideFoldersByUser": false,
        "divideFoldersByType": true,
        "saveImages": true,
        "saveVideos": true,
        "reactWhenDownloaded":false,
        "saveAudioFiles": true,
        "saveTextFiles": false,
        "saveOtherFiles": true,
        "savePossibleDuplicates": true,
        "filters": {
            "blockedExtensions": [
                ".htm",
                ".html",
                ".php",
                ".bat",
                ".sh",
                ".jar",
                ".exe"
            ]
        },
        "logLinks": {
            "destination": "/home/awildfrog/Share/memeverity/links",
            "destinationIsFolder": true,
            "divideLogsByServer": true,
            "divideLogsByChannel": true,
            "divideLogsByUser": true,
            "userData": true
        },
        "logMessages": {
            "destination": "/home/awildfrog/Share/memeverity/messages",
            "destinationIsFolder": true,
            "divideLogsByServer": true,
            "divideLogsByChannel": true,
            "divideLogsByUser": true,
            "userData": true
        }
    }
    ]
}`

**Comment by AnonymouseCow** [comment]
Ah it isnt formatting properly sorry for that, is there a way to make it look readable?

**Comment by get-got** [comment]
@AnonymouseCow

\`\`\`json
config here
\`\`\`
