### ISSUE TITLE
Wacky permissions on new folders

### ISSUE THREAD

**Issue by throwaway589** [get-got/discord-downloader-go#3]
I tried using this tool on linux and noticed a problem with the permissions on new folders: `d-wxrw---x` This means that the owner of the folder can't even read it.

The relevant line is: https://github.com/get-got/discord-downloader-go/blob/a3f760d951c6817c12ca9cd4d06f45797f7b4668/downloads.go#L440

That `755` should be `0755` as it's supposed to be an octal value.

Thanks for working on this project! It saves me so much time.

**Comment by get-got** [comment]
Thanks, forgot about that, fixed for v1.3.2. Pushing release now.

**Comment by throwaway589** [comment]
Awesome, I appreciate you fixing it so quickly.
