### ISSUE TITLE
Bot refuses to create config file

### ISSUE THREAD

**Issue by iamtekno75** [get-got/discord-downloader-go#31]
Hey! Sorry for more things to deal with, the bot seems to fail during the creation of the config file on initial launch. Maybe I'm doing things wrong? Attached is a screenshot of what it tells me
![image](https://user-images.githubusercontent.com/88256761/127755086-bed90af8-4fea-4999-9fc5-386763d2e5b0.png)

**Comment by get-got** [comment]
Yeah sorry about that, fixed it here: https://github.com/get-got/discord-downloader-go/commit/2e254b054d7d3fb8223fb4cfcdd0fb6e1450239a

Here's a windows build for it
[discord-downloader-go.zip](https://github.com/get-got/discord-downloader-go/files/6912089/discord-downloader-go.zip)

**Comment by iamtekno75** [comment]
thank you tons!
