### ISSUE TITLE
Failed to save new settings file...

### ISSUE THREAD

**Issue by Xlithan** [get-got/discord-downloader-go#32]
2021/08/03 22:09:45 config.go:644: [Setup] Failed to save new settings file...  open : The system cannot find the file specified.

Not sure what I'm missing.

**Comment by get-got** [comment]
> 
> 
> 2021/08/03 22:09:45 config.go:644: [Setup] Failed to save new settings file... open : The system cannot find the file specified.
> 
> Not sure what I'm missing.

@Xlithan Sorry about that, fixed: https://github.com/get-got/discord-downloader-go/commit/2e254b054d7d3fb8223fb4cfcdd0fb6e1450239a

Here's a windows build
[discord-downloader-go.zip](https://github.com/get-got/discord-downloader-go/files/6912089/discord-downloader-go.zip)
