### ISSUE TITLE
Request? Dropbox support and/or logging of links processed to file.

### ISSUE THREAD

**Issue by Ghestalt** [get-got/discord-downloader-go#35]
Hey. I was wondering if your fork handles (or you intend to add support for) dropbox links and also if it supports saving a log of links encountered to a log file for manual downloading if something isn't supported.

Cheers.

**Comment by get-got** [comment]
> 
> 
> Hey. I was wondering if your fork handles (or you intend to add support for) dropbox links and also if it supports saving a log of links encountered to a log file for manual downloading if something isn't supported.
> 
> Cheers.

For dropbox, I'll add it to the to-do list.

For logging links, you can setup something like this in the channel(s)/server(s) configs:

```json
"logLinks": {
    "destination": "log_links",
    "destinationIsFolder": true,
    "divideLogsByServer": true,
    "divideLogsByChannel": true,
    "divideLogsByUser": true,
    "userData": true
},
