### ISSUE TITLE
How to add multiple channels?

### ISSUE THREAD

**Issue by BlackWhite321** [get-got/discord-downloader-go#36]
I know this is kinda dumb question. I would like to download for example images from 5 chanels and won't open bot 5 times and 5 times edit settings file. Is there way to add this 5 channels 1 time and download it all by 1 command? I tried using ";" or "," between channels ID (in settings file). I couldn't find anything about it in TUT.

**Comment by get-got** [comment]
> 
> 
> I know this is kinda dumb question. I would like to download for example images from 5 chanels and won't open bot 5 times and 5 times edit settings file. Is there way to add this 5 channels 1 time and download it all by 1 command? I tried using ";" or "," between channels ID (in settings file). I couldn't find anything about it in TUT.

Follow the settings examples in the readme to see how to configure multiple channels.

For running a single command to process history from multiple channels, just separate by commas or use the `all` keyword. i.e. `ddg history 01, 02, 03, 04, 05` or `ddg history all`

**Comment by BlackWhite321** [comment]
> Follow the settings examples in the readme to see how to configure multiple channels.

So I've followed and still have a problem. Did I set something wrong? 
![image](https://user-images.githubusercontent.com/61238777/134567479-c969bd6b-eeb9-45f9-a5da-10429c7bf2de.png)
Error: 
![image](https://user-images.githubusercontent.com/61238777/134567577-271fb585-3250-4f39-b1ed-ec0f13c403e1.png)

Can you help me please?

**Comment by get-got** [comment]
> 
> 
> > Follow the settings examples in the readme to see how to configure multiple channels.
> 
> So I've followed and still have a problem. Did I set something wrong?
> ![image](https://user-images.githubusercontent.com/61238777/134567479-c969bd6b-eeb9-45f9-a5da-10429c7bf2de.png)
> Error:
> ![image](https://user-images.githubusercontent.com/61238777/134567577-271fb585-3250-4f39-b1ed-ec0f13c403e1.png)
> 
> Can you help me please?

The beginning should be "channels", not "channel"

**Comment by BlackWhite321** [comment]
> > > Follow the settings examples in the readme to see how to configure multiple channels.
> > 
> > 
> > So I've followed and still have a problem. Did I set something wrong?
> > ![image](https://user-images.githubusercontent.com/61238777/134567479-c969bd6b-eeb9-45f9-a5da-10429c7bf2de.png)
> > Error:
> > ![image](https://user-images.githubusercontent.com/61238777/134567577-271fb585-3250-4f39-b1ed-ec0f13c403e1.png)
> > Can you help me please?
> 
> The beginning should be "channels", not "channel"

Thanks, you helped me so much. Also I would like to ask also about to status function. Is it possible to don't show the status? I tried in your previous software to disable it but nothing worked.

**Comment by get-got** [comment]
> 
> 
> > > > Follow the settings examples in the readme to see how to configure multiple channels.
> > > 
> > > 
> > > So I've followed and still have a problem. Did I set something wrong?
> > > ![image](https://user-images.githubusercontent.com/61238777/134567479-c969bd6b-eeb9-45f9-a5da-10429c7bf2de.png)
> > > Error:
> > > ![image](https://user-images.githubusercontent.com/61238777/134567577-271fb585-3250-4f39-b1ed-ec0f13c403e1.png)
> > > Can you help me please?
> > 
> > 
> > The beginning should be "channels", not "channel"
> 
> Thanks, you helped me so much. Also I would like to ask also about to status function. Is it possible to don't show the status? I tried in your previous software to disable it but nothing worked.

@BlackWhite321 `"presenceEnabled": false,` in main section of settings
