### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by babedruth** [get-got/discord-downloader-go#37]
![major error test](https://user-images.githubusercontent.com/90550310/132981559-8f170a10-efd4-47d4-b98d-dca032acbd1e.png)

I've been running into this issue recently when I try to scrape any channel, regardless of the account, server, channel or person I've messaged. I've also tried re-downloading the program & resetting my settings from scratch... Any advice on a work around, or what I should do?

Command that triggered the error: "ddg history all"
(I own the server I'm trying to scrape, and I've made sure both Admin Channel & Channel were filled accordingly and properly.)

**Comment by get-got** [comment]
> 
> 
> ![major error test](https://user-images.githubusercontent.com/90550310/132981559-8f170a10-efd4-47d4-b98d-dca032acbd1e.png)
> 
> I've been running into this issue recently when I try to scrape any channel, regardless of the account, server, channel or person I've messaged. I've also tried re-downloading the program & resetting my settings from scratch... Any advice on a work around, or what I should do?
> 
> Command that triggered the error: "ddg history all"
> (I own the server I'm trying to scrape, and I've made sure both Admin Channel & Channel were filled accordingly and properly.)

Sorry about late reply, didn't get a chance until now. Can you send your config? Just remove any sensitive stuff

**Comment by jarrydstan** [comment]
I am getting the same issue, i will paste my config. 

{
	"credentials": {
		[REDACTED],
		[REDACTED],
		[REDACTED]
	},
	"admins": [
		[REDACTED],
		[REDACTED]
	],
	"adminChannels": [
		{
			"channel": [REDACTED]
		}
	],
	"debugOutput":true,
	"messageOutput": false,
	"commandPrefix": "ddg ",
	"allowSkipping": true,
	"scanOwnMessages": false,
	"githubUpdateChecking": true,
	"presenceEnabled": false,
	"presenceStatus":"",
	"reactWhenDownloaded": false,
	"channels": [
		{
			"channels": [REDACTED],
			"destination": "[REDACTED]",
			"enabled": true,
			"allowCommands": true,
			"errorMessages": true,
			"scanEdits": true,
			"ignoreBots": false,
			"updatePresence": false,
			"reactWhenDownloaded": false,
			"divideFoldersByType": true,
			"divideFoldersByChannel": true,
			"saveOtherFiles": false,
			"saveImages": true,
			"saveTextFiles": false,
			"savePossibleDuplicates" : false,
			"saveVideos": true
		}
	]
}
