### ISSUE TITLE
Discord login failed:  websocket: close 4004: Authentication failed.

### ISSUE THREAD

**Issue by deadstoned** [get-got/discord-downloader-go#41]
Hi there,

I've used the same Discord token that works with Seklfreak's version and I'm getting the following error:
Discord login failed:  websocket: close 4004: Authentication failed.

I use 2FA and take the token from the following location as always:
https://www.youtube.com/watch?v=YEgFvgg7ZPI

I've tried signing out and in to get new tokens, but get the same result.

My settings.json file are the following:
{
	"credentials": {
		"token": "mfa.blablablablablablablablablablablablablablablablablablablablabla",
		"twitterAccessToken": "your access token",
		"twitterAccessTokenSecret": "your access token secret",
		"twitterConsumerKey": "your consumer key",
		"twitterConsumerSecret": "your consumer secret",
		"flickrApiKey": "your flickr api key"
	},
	"admins": [
		"4668464563153153"
	],
	"adminChannels": [
		{
			"channel": "7896542571245687"
		}
	],
	"debugOutput": false,
	"messageOutput": false,
	"commandPrefix": "ddg ",
	"allowSkipping": true,
	"scanOwnMessages": false,
	"downloadRetryMax": 5,
	"downloadTimeout": 60,
	"githubUpdateChecking": true,
	"presenceEnabled": true,
	"presenceStatus": "online",
	"presenceType": 3,
	"reactWhenDownloaded": true,
	"servers": null,
	"channels": [
		{
			"channel": "245230842401440489",
			"destination": "K:\Downloaders\Discord\images"
		},
	]
}
7

**Comment by get-got** [comment]
Put `"userBot": true,` in the credentials section. Let me know if that fixes it

**Comment by Serph91P** [comment]
> Put `"userBot": true,` in the credentials section. Let me know if that fixes it

have the same error, downloader was working before. Now it only shows this message.

**Comment by Serph91P** [comment]
> > Put `"userBot": true,` in the credentials section. Let me know if that fixes it
> 
> have the same error, downloader was working before. Now it only shows this message.

ok looks like the token reset. fixed.

**Comment by modelfe** [comment]
I'm having this problem on Linux using a Bot Application with the following settings (in ~/discordgo/settings.json):

```
{
	"credentials": {
		"token": "xxxxxxxxxxxxxxxxxxx",
		"userBot": true
	},
	"admins": [
		"876274047791534100"
	],
	"adminChannels": [
		{
			"channel": "1093029617629134919"
		}
	],
	"githubUpdateChecking": true,
	"commandPrefix": "ddg ",
	"presenceEnabled": false,
	"presenceStatus": "idle",
	"channels": [
		{
			"channel": "1093022144893558837",
			"destination": "$HOME/Downloads/discordgo",
			"enabled": true,
			"save": true,
			"allowCommands": false,
			"scanEdits": true,
			"ignoreBots": false,
			"sendErrorMessages": false,
			"presenceEnabled": true,
			"reactWhenDownloadedHistory": false,
			"divideByType": true,
			"saveImages": true,
			"saveVideos": true
		}
	]
}
```
Then running:

```
cd $HOME/discordgo
$HOME/discordgo/discord-downloader-go_linux_amd64
```
Which results in:
```
2023/04/05 15:05:53 config.go:608: 	> [Settings] Loaded - bound to 1 channel, 0 categories, 0 servers, 0 users
2023/04/05 15:05:53 main.go:476: 	> [Database] Opening database...	(this can take a second...)
2023/04/05 15:05:53 main.go:506: 	> [Database] Database opened, contains 0 entries...
2023/04/05 15:05:53 main.go:664: 	> [Discord] Connecting to Discord via Token...
2023/04/05 15:05:53 main.go:614: 	> [API | Instagram] API credentials missing, the bot won't use the Instagram API.
2023/04/05 15:05:53 main.go:574: 	> [API | Twitter] API credentials missing, the bot won't use the Twitter API.
2023/04/05 15:05:55 main.go:631: 	> [Discord] Discord login failed:	websocket: close 4004: Authentication failed.
2023/04/05 15:05:55 common.go:29: 	> [EXIT IN 15 SECONDS] Uptime was 2 seconds 837 milliseconds 305 microseconds...
```
Any idea what's going on?

**Comment by get-got** [comment]
> I'm having this problem on Linux using a Bot Application with the following settings (in ~/discordgo/settings.json):
> 
> 
> 
> ```
> 
> {
> 
> 	"credentials": {
> 
> 		"token": "xxxxxxxxxxxxxxxxxxx",
> 
> 		"userBot": true
> 
> 	},
> 
> 	"admins": [
> 
> 		"876274047791534100"
> 
> 	],
> 
> 	"adminChannels": [
> 
> 		{
> 
> 			"channel": "1093029617629134919"
> 
> 		}
> 
> 	],
> 
> 	"githubUpdateChecking": true,
> 
> 	"commandPrefix": "ddg ",
> 
> 	"presenceEnabled": false,
> 
> 	"presenceStatus": "idle",
> 
> 	"channels": [
> 
> 		{
> 
> 			"channel": "1093022144893558837",
> 
> 			"destination": "$HOME/Downloads/discordgo",
> 
> 			"enabled": true,
> 
> 			"save": true,
> 
> 			"allowCommands": false,
> 
> 			"scanEdits": true,
> 
> 			"ignoreBots": false,
> 
> 			"sendErrorMessages": false,
> 
> 			"presenceEnabled": true,
> 
> 			"reactWhenDownloadedHistory": false,
> 
> 			"divideByType": true,
> 
> 			"saveImages": true,
> 
> 			"saveVideos": true
> 
> 		}
> 
> 	]
> 
> }
> 
> ```
> 
> Then running:
> 
> 
> 
> ```
> 
> cd $HOME/discordgo
> 
> $HOME/discordgo/discord-downloader-go_linux_amd64
> 
> ```
> 
> Which results in:
> 
> ```
> 
> 2023/04/05 15:05:53 config.go:608: 	> [Settings] Loaded - bound to 1 channel, 0 categories, 0 servers, 0 users
> 
> 2023/04/05 15:05:53 main.go:476: 	> [Database] Opening database...	(this can take a second...)
> 
> 2023/04/05 15:05:53 main.go:506: 	> [Database] Database opened, contains 0 entries...
> 
> 2023/04/05 15:05:53 main.go:664: 	> [Discord] Connecting to Discord via Token...
> 
> 2023/04/05 15:05:53 main.go:614: 	> [API | Instagram] API credentials missing, the bot won't use the Instagram API.
> 
> 2023/04/05 15:05:53 main.go:574: 	> [API | Twitter] API credentials missing, the bot won't use the Twitter API.
> 
> 2023/04/05 15:05:55 main.go:631: 	> [Discord] Discord login failed:	websocket: close 4004: Authentication failed.
> 
> 2023/04/05 15:05:55 common.go:29: 	> [EXIT IN 15 SECONDS] Uptime was 2 seconds 837 milliseconds 305 microseconds...
> 
> ```
> 
> Any idea what's going on?

@modelfe Make sure your token hasn't been reset, sometimes that happens. If it persists maybe try the same token on a different bot application just to see if it's a problem with the application or your bot account. If it seems to be the application let me know and I'll try to figure it out.

The userBot setting was deprecated with v2, that's not effecting anything in case that was a concern, the program's ignoring it.
