### ISSUE TITLE
Files disappearing if deleted on discord

### ISSUE THREAD

**Issue by jarrydstan** [get-got/discord-downloader-go#42]
I'm not sure if it's a setting I have missed, but after the bot has downloaded an image or video, if the message is then deleted in discord it deleted it from the files for some reason. Is this a bug or is there a way to turn it off?

**Comment by get-got** [comment]
Sorry for such a late reply

The bot doesn't actually have any functions used that could or would delete/replace files. If you encountered this it must have been some very strange bug.
