### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by DerikVen** [get-got/discord-downloader-go#46]
Hi,

Really enjoying the program this far, works without issues but something I though of that would be useful is the ability to forward instead of downloading media to another discord server/channel, we all have limited space on our PC's and keeping content on a discord server would solve that issue and it might not be that difficult (please correct me if I'm wrong), only issue is that I unfortunately don't understand any of the coding :(

**Comment by get-got** [comment]
@DerikVen This has been introduced with : https://github.com/get-got/discord-downloader-go/commit/7c0afe0df82e490f7a9b08f905ad834171ff6986

**Comment by get-got** [comment]
And pair with https://github.com/get-got/discord-downloader-go/commit/cd751274bb533e745730028982735de04492e52f to disable saving of files
