### ISSUE TITLE
Can't download image files which are tagged with SPOILER

### ISSUE THREAD

**Issue by Sart-Hack** [get-got/discord-downloader-go#47]
![Screenshot (76)](https://user-images.githubusercontent.com/84909986/163698497-0cdbc26b-6682-44c0-b7f3-16fd9e755530.png)

**Comment by get-got** [comment]
@Sart-Hack I just tried this with \|\| tags and directly sending files and marking as spoilers, both times it handled fine and named them SPOILER_XXXXXXXXXXX. Is this consistent for you?
