### ISSUE TITLE
Randomly pings people

### ISSUE THREAD

**Issue by ToaSt3635** [get-got/discord-downloader-go#48]
The program pings a random person at random intervals, in a specific channel I have it set to. I have it set to download from multiple channels and yet it picks the same one to ping in every time, it isn't even the channel I'm in that it pings, either. it doesn't even seem like it's picking a person who's online. Another weird thing is that spam pings the same person if i use the ctrl+c to close hotkey, and it won't even close itself out. Nothing seems to stop it from pinging people except using task manager or pressing the "X" button.

**Comment by get-got** [comment]
@ToaSt3635 I've never heard of this happening to anyone so far, can you enable debugOutput and send the output when this happens?

**Comment by birdofhermes** [comment]
This happens for me if the picture for whatever reason is not saveable (long filename mostly) and pings the author.

**Comment by get-got** [comment]
@ToaSt3635 I now realize it was probably sending error messages due to download failure or something, but until recently it would send blank messages when using the bot as a userbot, that's fixed now so it shouldn't just be an empty message pinging them.

**Comment by get-got** [comment]
> This happens for me if the picture for whatever reason is not saveable (long filename mostly) and pings the author.

@birdofhermes ``"errorMessages": false,`` in channel/server configs. There currently isn't a global setting for it.
