### ISSUE TITLE
Issue with file names

### ISSUE THREAD

**Issue by macarooni-man** [get-got/discord-downloader-go#5]
I am using this to download a specific file type (its a text file with parameters) that isn't really accounted for, although it refuses to save the file name; "Date InvalidName.asm" Is there a way to get it to correctly grab the name?

Edit; I checked the original program and the same exact thing was happening. It seems to be a MIME mismatch. I am not sure how to get this file type to properly download though, any help would be appreciated.

**Comment by get-got** [comment]
@macarooni-man Can you give me an example filename it would have, so I can try and replicate it for testing?

It only uses InvalidFilename if it doesn't detect the input as a filename with regex, so it's weird that it's doing that.

**Comment by macarooni-man** [comment]
Yeah for sure, I'll give a more detailed description. So essentially the file type I am using is a preset file for a VST plugin, it just loads the settings of the synth with a list in a text file with the extension ".vital". I modified the source code of the original program to allow it to download the patch from discord and it did the same thing with that one too. Here's what is happening with my modified version of the original;

![pic 1](https://user-images.githubusercontent.com/72526467/100550285-8a9f7800-323e-11eb-8333-bf5184828147.png)

![pic 2](https://user-images.githubusercontent.com/72526467/100550322-c0dcf780-323e-11eb-8873-10f0827a7e1e.png)

With your version;

![pic 3](https://user-images.githubusercontent.com/72526467/100550650-08fd1980-3241-11eb-9fa8-17af251a93ce.png)

![pic 4](https://user-images.githubusercontent.com/72526467/100550657-13b7ae80-3241-11eb-879d-68ed52a8c921.png)


It's interesting because it saves the file in a working state. I wrote a PowerShell script that loops in the output folder to change the file extension while that program is open and the presets work, it's just that the name isn't saved (so jank LOL). But anyway I read through the code and it looks like the issue lies somewhere around line ~1020. I am not new to programming but I have no idea how to use golang syntax haha. Thanks for your help.

**Comment by macarooni-man** [comment]
I believe I have fixed it, I took a peek into the regex file and I found this;
REGEXP_FILENAME = `^^[^/\\:*?"<>|]{1,150}\.[A-Za-z0-9]{2,4}$$`

The last part {2,4} I guessed that it was a limit for the file extension in characters and voila I bumped the 4 up to 5 and it works fine. I don't know how many file extensions actually have 5 characters but maybe it's something to consider.

**Comment by get-got** [comment]
@macarooni-man So changing the max to 5 completely fixed your issue?

**Comment by macarooni-man** [comment]
Yeah for sure

**Comment by get-got** [comment]
Glad you figured it out! I changed it to 2,5 for the next release.

**Comment by Hackebein** [comment]
I just hit the same problem. I would recommend to completely remove the limits for file extensions because file extensions doesn't follow any pattern.
Here is a list of many known file extensions: https://en.wikipedia.org/wiki/List_of_filename_extensions 
Here some examples for common file extension:
> .c--/.h--
> .c++/.h++
> .dochtml/.docmhtml/.dothtml
> .torrent
> .unitypackage
> .vbox-extpack

**Comment by get-got** [comment]
> 
> 
> I just hit the same problem. I would recommend to completely remove the limits for file extensions because file extensions doesn't follow any pattern.
> Here is a list of many known file extensions: https://en.wikipedia.org/wiki/List_of_filename_extensions
> Here some examples for common file extension:
> 
> > .c--/.h--
> > .c++/.h++
> > .dochtml/.docmhtml/.dothtml
> > .torrent
> > .unitypackage
> > .vbox-extpack

https://github.com/get-got/discord-downloader-go/commit/5559230207ceab7030f39b206f7db9d9cc0502d7
