### ISSUE TITLE
New feature idea -- AdministratorPower

### ISSUE THREAD

**Issue by GroundPower** [get-got/discord-downloader-go#50]
i added to my version, if you wanna check it i can send codes and its perfectly fine right now.

If some guild user got administrator power, they can use commands but if you do "AdministratorPower = false", they cant.  
![resim_2022-05-29_012512891](https://user-images.githubusercontent.com/16006435/170844587-4b7d1540-1eda-4774-86cb-5effe4ddc853.png)
Check it please, maybe you can like it.

**Comment by get-got** [comment]
Resolved with https://github.com/get-got/discord-downloader-go/commit/8a626d2a9f80893c6bbf7872740dc9675ad3b055
