### ISSUE TITLE
selbot download history possible?

### ISSUE THREAD

**Issue by deadcode0815** [get-got/discord-downloader-go#51]
Is there a way to download history via selfbot?
I know about the bot commands, but can't figure out how this would work with selfbot

**Comment by get-got** [comment]
@deadcode0815 See the Settings Examples in the readme, there's a Selfbot section

**Comment by rktfier** [comment]
You specify a discord server channel (aka. Admin Channel) of your own which you send commands to, and the bot reads from there. Currently using it without any problems.
