### ISSUE TITLE
Feature suggestion: Filter download by user

### ISSUE THREAD

**Issue by acheong08** [get-got/discord-downloader-go#53]
Is it possible to download history and filter by user?

**Comment by Leebo-missile** [comment]
I was also wondering I would like to download only images mentioend @ a specific user, such as images mentioned to @username

**Comment by get-got** [comment]
@acheong08 @Leebo-missile 

```json
{
	"channels":
	{
		{
			"destination": "x",
			"channel": "123456789012345678",
			"filters":
			{
				"allowedPhrases": [ "<@user:id>", "hello" ],
				"allowedUsers": [ "123456789012345678", "123456789012345678" ]
			}
		}
	}
}
```

allowedPhrases if used without blockedPhrases, no messages will be processed unless they contain an allowed phrase.
allowedUsers will ONLY process messages if they were sent from the following users.
