### ISSUE TITLE
Feature suggestion: Option (toggle) to prevent redownloading of already-downloaded files

### ISSUE THREAD

**Issue by Drakonas** [get-got/discord-downloader-go#54]
I am not sure if the "filterDuplicates" setting in the LogLinks section actually addresses this, as I think that's just for logging messages, but correct me if I'm wrong.

It would be nice to have a way for it to allow me to delete/rename certain images in the folder, and not redownload them when I run ddg history all.

A lot of images I am downloading have messed up extensions, but also I am trying to keep duplicates out of my folders, as I have some favorites in a separate folder that come from the same Discord channel, and software I use rely on there being no duplicates.

Thus, I often rename/move them out of the folder to fix these issues... However, if I run ddg history all, the tool just treats them as missing downloads, and redownloads them.

Would there be a way to have the tool prevent downloading files that have already been downloaded? To me, this seems the most straight-forward method, and it would help people with a variety of situations, I feel, and would be beneficial to others that don't have my exact use case.

From a coding perspective, it seems the tool registers that the files are missing and updates the database... maybe this would be as simple as a toggle to prevent it from doing said changes to the database?

Thank you.

**Comment by get-got** [comment]
`"filterDuplicates": true` will make it skip any file that matches an existing exact filename (date timestamp included).

Though when a file is fully downloaded, the url is logged in the database and the bot shouldn't attempt to redownload any urls logged there, unless you delete(d) your database folder.

**Comment by Drakonas** [comment]
> Though when a file is fully downloaded, the url is logged in the database and the bot shouldn't attempt to redownload any urls logged there, unless you delete(d) your database folder.

This is not the case. It redownloads any file I delete when I have loglinks not enabled.

> `"filterDuplicates": true` will make it skip any file that matches an existing exact filename (date timestamp included).
That's what I needed to know. Thanks.
