### ISSUE TITLE
Is it possible to bypass Twitter requirements using Nitter?

### ISSUE THREAD

**Issue by rktfier** [get-got/discord-downloader-go#58]
The current Twitter image download implementation requires the user to have an active Twitter account, and provide their phone number to Twitter in order to get a developer account. I was wondering if it would be possible to use Nitter instead of Twitter to receive images, removing the requirement of Twitter credentials.

**Comment by get-got** [comment]
@rktfier I just checked it out, seems pretty cool, I'll implement when I get time soon.

**Comment by get-got** [comment]
Integration of github.com/n0madic/twitter-scraper  accomplishes this.

https://github.com/get-got/discord-downloader-go/commit/cdeebd83e6299414eaad538dd1393090869d41ec
