### ISSUE TITLE
parse error ("destination" folder)

### ISSUE THREAD

**Issue by eksynn** [get-got/discord-downloader-go#6]
I'm trying to get every image and video shared to me by my fiancée, from the very beginning
is there a discord server where i might be able to get help from more quickly?

I'm getting an error if i put a location into the settings ⇓
![image](https://user-images.githubusercontent.com/15912296/101086677-f875d780-358f-11eb-9794-5bc6f34e6798.png)

it seems to be expecting something else:
```
Error: Parse error on line 25:
...,			"destination": "Y:\Discord Stuff\In
----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
```

```js
,
	"channels": [
		{
			"channel": "135133384786575361",
			"destination": "Y:\Discord Stuff\Inbound",
			"enabled": true,
			"allowCommands": true,
			"errorMessages": true,
			"scanEdits": true,
			"updatePresence": true,
			"reactWhenDownloaded": false,
			"divideFoldersByType": true,
			"saveImages": true,
			"saveVideos": true
		}
	]
```

**Comment by eksynn** [comment]
is there a discord server where i might be able to get help from more quickly?

**Comment by eksynn** [comment]
```js
,
	"channels": [
		{
			"channel": "135133384786575361",
			"destination": "Y:\Discord Stuff\Inbound",
			"enabled": true,
			"allowCommands": true,
			"errorMessages": true,
			"scanEdits": true,
			"updatePresence": true,
			"reactWhenDownloaded": false,
			"divideFoldersByType": true,
			"saveImages": true,
			"saveVideos": true
		}
	]```

**Comment by get-got** [comment]
@eksynn It's likely because you're using backslashes in the path. Try changing those to slashes and see if that solves it.

[If you need more help, here's the discord server for this project](https://discord.com/invite/6Z6FJZVaDV)

**Comment by eksynn** [comment]
so for future reference, get-got was very helpful in the discord server and helped me fix the issues I've been having ( ◠ ‿◠) closing issue o/
this one in specific was resolved by replacing `\` with `\\` in every instance of the folder name.
