### ISSUE TITLE
Neither Token nor normal login working

### ISSUE THREAD

**Issue by scryptio** [get-got/discord-downloader-go#60]
using
"email" and "password" I get

`Error logging in: Unable to fetch discord authentication token. HTTP 400 Bad Request, {"captcha_key": ["captcha-required"], "captcha_sitekey": "xxx", "captcha_service": "hcaptcha"}`

using "selfbot": true, "token": "XxXXxXXxxX:adwWAWDd/AWDWd323awd+aawdWDHUiuawzdDWjkhj/awdWAHDkjahwdjn+1337/hbDKJWAHDukwahkjdh/jdwKLAJD/awjkdilWADU892ujKDWAMJKl/HMsc="

Yes, the token I get from CTRL SHIFT I -> Application -> Storage -> Local Storage -> https://canary.discord.com (in this case)" -> token, just looks like this. 

-> `Discord login failed:        websocket: close 4004: Authentication failed.`

So... How to get either the token or login working properly?

**Comment by DisasterInbound** [comment]
Hi there

I got my own token for the selfbot from a different place. 

Open Console > Network Tab > filter posts with "/api" and reload the page > click on "library?country_code" and look for authorization on the Headers tab.

**Comment by scryptio** [comment]
@get-got Why was this NEVER added to the readme despite being the correct way to get the token? The way described how to do it currently is wrong and you get a token you simply cannot use

**Comment by get-got** [comment]
i'll add it calm the fuck down

**Comment by scryptio** [comment]
C&P stuff doesn't work -> people complain -> calm the fuck down

got it

**Comment by get-got** [comment]
> C&P stuff doesn't work -> people complain -> calm the fuck down
> 
> 
> 
> got it

It was moreso your bitchy tone when asking for help on a free project.
