### ISSUE TITLE
"Message is corrupted due to endpoint restriction"

### ISSUE THREAD

**Issue by Bubbline5** [get-got/discord-downloader-go#61]
After not using the program for a while and updating to 1.6.5, any message sent in a bound channel or the admin channel results in a debug error message reading "Message is corrupted due to endpoint restriction, and attempts to fix seem to have failed..." and not executing any commands or downloading any images. 

I have no idea what this means or how to fix it, and I can't find any information online that helps.

**Comment by StrikS** [comment]
Same problem. I have never used discord downloader before. I tried it today and got the same error. Checked configs several times, should be correct. Also tried all previous releases on windows v1.6.1-v1.6.5, the error is still there.

**Comment by EpicKitty666** [comment]
Discord added a toggle on the developer portal to toggle the bot's ability to read message conetent, I had the same error until It was toggled on. (Thank you to get-got on discord)
![image](https://user-images.githubusercontent.com/47422728/190854559-d401740e-4988-4261-999f-16b688ca5781.png)
