### ISSUE TITLE
Bot can't respond to private channels in 1.3.7

### ISSUE THREAD

**Issue by DevilPF** [get-got/discord-downloader-go#7]
In last version 1.3.7 bot can't respond to private message channel (direct message to bot user):

2020/12/20 16:16:43.950019 discord.go:245: Failed to check permissions (2048) for 412985156786192384:   HTTP 404 Not Found, {"message": "404: Not Found", "code": 0}
2020/12/20 16:16:43.959016 commands.go:94: [dgrouter:help] Bot does not have permission to send messages in 412985156786192384

It fails to send message and also fails to do the command (history, help, etc)

1.3.6 is working properly
The channel is in adminChannels

**Comment by get-got** [comment]
@DevilPF I see why, thank you for including the output. I'll add checks for if it's actually a server channel prior to checking permissions to avoid that. It'll be fixed in 1.3.8.

**Comment by get-got** [comment]
Fixed https://github.com/get-got/discord-downloader-go/commit/6015c739dc6f8931bc708facb1b0343c94432e9a

**Comment by DevilPF** [comment]
Excelent, thank you, 1.3.8 is working as intended.
