### ISSUE TITLE
[Feature request] Discord thread support

### ISSUE THREAD

**Issue by j4pa0** [get-got/discord-downloader-go#72]
Hi, is there any chance for the bot to support downloading thread channel in the future? It says "BOT DOESN'T HAVE PERMISSION TO READ MESSAGE HISTORY" when i try to download with an ID of a thread. I'm using self-bot. Thanks!

**Comment by get-got** [comment]
@j4pa0 I can check this out again but I recall updating to the oldest version of discordgo that supports threads will still remove the ability to use selfbots, only genuine discord bots.

**Comment by xTeooo** [comment]
im interesed on this too since thread support seems to importand to me ( half of servers which i'm watching are made in Threads way)
There is a chance to add thread support to the current version of bot ? Only here or in a different branch ?

**Comment by Cronosus** [comment]
it may be digging corpse, but is it planned for userbot thread support?
as i can see its only for normal bot, and i have no idea how to make bot that can join someone elses server and then download files there.
