### ISSUE TITLE
[Feature Request] Skipping

### ISSUE THREAD

**Issue by Laccsss** [get-got/discord-downloader-go#73]
Sometimes I'm scraping entire servers, would nice to be able to skip the current channel that it's downloading from by using a skip command perhaps. 

Sometimes it starts downloading from welcome channels or the general chat etc.. which takes painfully long, so it would be cool to just be able to skip it!

**Comment by get-got** [comment]
> 

@Laccsss It's a bit more of a hassle but `ddg history <id> cancel` accomplishes this.
