### ISSUE TITLE
Downloading old Image and video didn't work

### ISSUE THREAD

**Issue by Suttichok136** [get-got/discord-downloader-go#74]
Hi, I am trying to use this tool to download some old images and videos from the discord channel. When I run the application and type in the command `ddg history all`, this is the result.

`Command — History

2 seconds: 0 total files downloaded!
178 total messages processed

Server: ***
Channel: #***

FINISHED!
Ran 2 message history requests

Duration was 2 seconds 878 milliseconds 501 microseconds `

I check the destination folder but there is no file in it.
Could you help me fix it?

This is my setting.json

	"credentials": {
		"token": "***",
		"userbot": true
	},
	"admins": [ "***" ],
	"adminChannels": [
		{
			"channel": "***"
		}
	],
	"debugOutput": true,
	"messageOutput": false,
	"commandPrefix": "ddg ",
	"allowSkipping": true,
	"scanOwnMessages": false,
	"downloadRetryMax": 5,
	"downloadTimeout": 60,
	"githubUpdateChecking": true,
	"presenceEnabled": true,
	"presenceStatus": "online",
	"presenceType": 3,
	"reactWhenDownloaded": true,
	"servers": null,
	"channels": [
		{
			"channel": "***",
			"destination": "***",
			"overwriteAllowSkipping": false,
            "saveImages": true,
            "saveVideos": true,
            "saveAudioFiles": true,
            "saveTextFiles": false,
            "saveOtherFiles": false
		}
	]

**Comment by get-got** [comment]
@Suttichok136 "userBot", not "userbot". Settings are case sensitive.

**Comment by Suttichok136** [comment]
I change it to "userBot" and it still not downloading any image files. I tried to run the bot on a channel that has only 2 messages, 1 with text and 1 with an image. The bot read both messages but not downloading the message with the image.

**Comment by Serph91P** [comment]
> I change it to "userBot" and it still not downloading any image files. I tried to run the bot on a channel that has only 2 messages, 1 with text and 1 with an image. The bot read both messages but not downloading the message with the image.

Have the kinda the same issue. I had it setup and running before and was working fine. But One channel it just downloads to a specific point and says its finished. But there are alot missing. Almost like it stopped at a specific date.
