### ISSUE TITLE
Stop downloading Gifs

### ISSUE THREAD

**Issue by NeverHappy25** [get-got/discord-downloader-go#75]
Is ther any methode to stop downloading gifs?
Or just download mp4, mov ... and not all videos?

**Comment by get-got** [comment]
> Is ther any methode to stop downloading gifs?
> 
> Or just download mp4, mov ... and not all videos?

Follow this example (the bottom part of it, blockedExtensions)

![image](https://user-images.githubusercontent.com/43052079/197878606-d80a053d-a63c-4e94-975d-c01d8808e57e.jpeg)
