### ISSUE TITLE
History not downloading everything

### ISSUE THREAD

**Issue by Serph91P** [get-got/discord-downloader-go#78]
with the command ddg history all its downloading but stops or marks as completed even there are some Messages/Pictures missing (the most recent ones). If new Messages get posted they will be downloaded correctly.

**Comment by get-got** [comment]
> with the command ddg history all its downloading but stops or marks as completed even there are some Messages/Pictures missing (the most recent ones). If new Messages get posted they will be downloaded correctly.

@Serph91P Try deleting the cache folder then running history.

**Comment by Serph91P** [comment]
> > with the command ddg history all its downloading but stops or marks as completed even there are some Messages/Pictures missing (the most recent ones). If new Messages get posted they will be downloaded correctly.
> 
> @Serph91P Try deleting the cache folder then running history.

get this error now cannot login anymore?
`Discord login failed:	strconv.ParseInt: parsing "1669050695.765": invalid syntax`

**Comment by Serph91P** [comment]
> > with the command ddg history all its downloading but stops or marks as completed even there are some Messages/Pictures missing (the most recent ones). If new Messages get posted they will be downloaded correctly.
> 
> @Serph91P Try deleting the cache folder then running history.

OK after deleting the db it worked again.
