### ISSUE TITLE
Text Messages are not exported

### ISSUE THREAD

**Issue by adnoh** [get-got/discord-downloader-go#81]
Maybe I misinterpret and the feature is not existing,
but it does not export the actual messages in the selected channel.
Attachements work great, but the messages seems to only go into the database or cache.
It would be super Handy to also keep track of the messages - either which where part of the Attachement - or in general to export the messages.
Thanks.

**Comment by drachedachte1** [comment]
ye u did
its only for downloading media like pictures

**Comment by get-got** [comment]
@adnoh I'm confused by what you mean, what are you trying to download?

@drachedachte1 this version can download any kind of file

**Comment by adnoh** [comment]
thanks - I guess @drachedachte1 cleared it up for me. 
@get-got I thought it's also possible to extract the text(=chat) messages which are not an attachment. For example if you have a channel where let's say you communicate with a bot by a message in that channel and the bot responds with a file - it would be good to also save that prompt to the bot (the bot repeats your message when it sends the created file) next to the file on disk - so if you want to recreate it or want to search for specific text patterns - you can.

**Comment by get-got** [comment]
> 

This may be what you're looking for: https://github.com/Tyrrrz/DiscordChatExporter

**Comment by adnoh** [comment]
thanks @get-got I know such tools but then I have a disconnection between file and message again. 
Never mind maybe it's just some wired and special usecase on my side where I want to be able to search the downloaded files for context or even better declare a message (like "context" of the file) filter to specify if something gets downloaded or not. Think on midjourney or stable diffusion servers for example. If you're doing conecpt art on a gamen environment for example you're intrested in prompts sb. used for creating exactly that and to not download everything. Also to find it again on your local disk later when you need to do some mood boards - you could just grep or find the keywords you're looking for.
But I guess we can close this - it's maybe a too special thing I need here. I'll continue using the search function in discord which is really a pain in the ... when you try to be creative ;)
