### ISSUE TITLE
[Feature Request] More options in filenamecaption

### ISSUE THREAD

**Issue by xTeooo** [get-got/discord-downloader-go#83]
Adding more options to customize SendFile message in filenamecaptions like :
Servername
Filename
Filesize
Byauthor
All form of dates

**Comment by get-got** [comment]
@xTeooo I will add everything else but dates already work, see here
![image](https://user-images.githubusercontent.com/43052079/210180635-5d693146-4183-4c67-8ed7-d202be89c5c7.png)

**Comment by xTeooo** [comment]
Okej thanks @get-got 🤩
