### ISSUE TITLE
Panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by SRoy89** [get-got/discord-downloader-go#84]
What does this error mean? I was fine but it randomly broke a couple of days earlier. Please let me know if there's more info needed, I'll provide them. Thanks.

>   ./ddg
> 2023/01/13 21:17:12 main.go:60: -------------------- Welcome to discord-downloader-go v1.6.8 --------------------
> 2023/01/13 21:17:12 main.go:61: [Version] go1.19.3 / discord-go v0.22.0 / Discord API v6
> 2023/01/13 21:17:12 main.go:75: [Info] ** Need help? Discord: https://discord.gg/6Z6FJZVaDV **
> 2023/01/13 21:17:12 config.go:367: [Settings] Loading from "settings.json"...
> 2023/01/13 21:17:12 main.go:83: [Settings] Loaded - bound to 0 channels and 0 servers
> 2023/01/13 21:17:12 main.go:91: [Database] Opening database...
> panic: runtime error: makeslice: len out of range
> 
> goroutine 1 [running]:
> github.com/HouzuoGuo/tiedot/data.(*Collection).Read(0xc0001660f0, 0x817151)
>         P:/Projects/Go/pkg/mod/github.com/!houzuo!guo/tiedot@v0.0.0-20200330175510-6fb216206052/data/collection.go:47 +0x106
> github.com/HouzuoGuo/tiedot/data.(*Partition).ForEachDoc(0xc0002105a0, 0xc0000952b0?, 0xc0005bf6e8?, 0xc00042f718)
>         P:/Projects/Go/pkg/mod/github.com/!houzuo!guo/tiedot@v0.0.0-20200330175510-6fb216206052/data/partition.go:133 +0x94
> github.com/HouzuoGuo/tiedot/db.(*Col).forEachDoc(0xc000164050, 0xabc420?, 0x50?)
>         P:/Projects/Go/pkg/mod/github.com/!houzuo!guo/tiedot@v0.0.0-20200330175510-6fb216206052/db/col.go:116 +0x219
> github.com/HouzuoGuo/tiedot/db.(*Col).ForEachDoc(...)
>         P:/Projects/Go/pkg/mod/github.com/!houzuo!guo/tiedot@v0.0.0-20200330175510-6fb216206052/db/col.go:127
> main.dbDownloadCount()
>         P:/Projects/Go/src/github.com/get-got/discord-downloader-go/database.go:82 +0x65
> main.main()
>         P:/Projects/Go/src/github.com/get-got/discord-downloader-go/main.go:120 +0xd65

**Comment by get-got** [comment]
@SRoy89 Your database got corrupted. If for some reason you have an older backup of it you can swap to that, otherwise delete the database folder and let the recording start fresh. If the files are in the matching destinations it won't re-save them.
