### ISSUE TITLE
ImageDownloader 1.6.8 has illegal instruction error when running on an Rpi Zero W

### ISSUE THREAD

**Issue by AbhiMayadam** [get-got/discord-downloader-go#85]
My issue is just that. I am assuming that you dropped armv6/32bit support in 1.6.8? 1.6.7 works fine on the Pi Zero W.

**Comment by get-got** [comment]
@AbhiMayadam No support was dropped. I just tested the latest rendition of my rewrite and it works fine on my Pi 3.

Builds for the rewrite beta are in #beta-v2-readme at https://discord.gg/6Z6FJZVaDV

Once I have more changed it'll be merged with the main branch. If it persists with the beta builds re-open this issue.

**Comment by AbhiMayadam** [comment]
So I ran your executable through gdb and this was my result. I am not an expert at assembly debugging so make of it what you will.

```(gdb) run
Starting program: /home/pi/ImageDownloader/testing

Program received signal SIGILL, Illegal instruction.
runtime.check () at C:/Program Files/Go/src/runtime/runtime1.go:152
152     C:/Program Files/Go/src/runtime/runtime1.go: No such file or directory.
(gdb) bt
#0  runtime.check () at C:/Program Files/Go/src/runtime/runtime1.go:152
#1  0x0007d218 in runtime.rt0_go () at C:/Program Files/Go/src/runtime/asm_arm.s:158
(gdb) display/i $pc
1: x/i $pc
=> 0x5ec30 <runtime.check+24>:  vmov.f32        s0, #112        ; 0x3f800000  1.0
(gdb)```

vmov.f32 is an instruction found on all VFP systems, but it can only copy from immediate constraints on VFPv3. 
My Pi Zero W does support VFP, but only up to VFPv2. I don't know what register is s0, but all I could find for that register is for stuff on armv8a, which is a thing on the Pi 3.

**Comment by AbhiMayadam** [comment]
Update to this: the compiler, gox,  used for this software targets armv7, and not armv6 like before the update. The code has to be recompiled with get-got's version of gox and the architecture must be specificed when compiling for arm.
