### ISSUE TITLE
error 401

### ISSUE THREAD

**Issue by Cronosus** [get-got/discord-downloader-go#86]
Hello
i have problem that when i try to download it just return this error:
`Error requesting messages: HTTP 401 Unauthorized, {"message": "401: Unauthorized", "code": 0}`

**Comment by get-got** [comment]
@Cronosus Typically that means either your bot lacks sufficient permissions in Discord to view the channel/messages, or the ID was entered incorrectly

**Comment by get-got** [comment]
Try `"checkPermissions": false,` in the main settings area

**Comment by Cronosus** [comment]
still the same
i even chcecked admin channel permission, it has admin role... all permision in admin channel ok. in read channel i have read and write too.. i really dont get it where is problem. :D

**Comment by get-got** [comment]
> still the same
> 
> i even chcecked admin channel permission, it has admin role... all permision in admin channel ok. in read channel i have read and write too.. i really dont get it where is problem. :D
> 
> 

The main branch you downloaded the program from is being replaced with an overhaul update, join the discord in the readme for this project and see the #beta-v2-builds channel. If it doesn't work with that version I can help pinpoint it

**Comment by Cronosus** [comment]
> > still the same
> > i even chcecked admin channel permission, it has admin role... all permision in admin channel ok. in read channel i have read and write too.. i really dont get it where is problem. :D
> 
> The main branch you downloaded the program from is being replaced with an overhaul update, join the discord in the readme for this project and see the #beta-v2-builds channel. If it doesn't work with that version I can help pinpoint it

i should do that sooner.. :D
beta build works
