### ISSUE TITLE
Extend functionality to repost media to designated channel

### ISSUE THREAD

**Issue by UnconsciousPebble** [get-got/discord-downloader-go#89]
Would it be possibly to add the functionality of having the bot repost the scraped media (attachments and links) to a separate channel, ideally while preserving the original poster's name tag and comment?
The purpose of this would be to collect scattered user posts, such as art, memes, videos etc. that are posted in #general or unrelated channels and automatically sort them into a media channel for later consumption/archival.

**Comment by get-got** [comment]
Sorry for late reply, I have these settings in the readme but I need to add documentation for the keys:

sendFileCaption can take `"{{channelID}}"`. `"{{serverID}}"`, `"{{channelName}}"`. I'll add more at some point.

![image](https://user-images.githubusercontent.com/43052079/228421069-c3e74ddf-8ddb-4996-9d74-75d674254181.png)
