### ISSUE TITLE
[Suggestion] Can we get a docker container for this?

### ISSUE THREAD

**Issue by nmills3** [get-got/discord-downloader-go#9]
i've been using this image downloader to backup chats in my discord server but it's a bit of a pain having to keep an instance of windows running just for this to run on. Would it be possible for you to make a docker image to do the same thing?

**Comment by drachedachte1** [comment]
u can just minimise it?

just add the docker itself :D 
i honestly dont think anybody would code that but if somebody does +rep i wont use it but great job

and how is it a pain to have 1 window minimised to task bar? like i would understand if u would have said "its a bit of a pain that it takes away internet" duh its a program that needs to connect to a internet service and downloads media like comon

Unofficial image downloader support server
 https://discord.gg/d8MYEC6

**Comment by nmills3** [comment]
It's a pain because i have a server running unraid and currently i run an entire windows vm just to run this one program to backup images from my discord server

**Comment by drachedachte1** [comment]
why dont u just back your server up once a day?
like u run it once a day and use history command and then when its done u can rest?
or maybe even only run it every few days
it dosent need to get every new pic 24/7

**Comment by nmills3** [comment]
Well for that to work i either need to setup the vm to auto boot once every x hours/days run the script and the shutdown and that is already relying on windows to actually start which is already hit or miss because of updates and stupid here's whats new screens blocking start up pograms or i would have to leave windows running and schedule the program to run every x hours/days which would require leaving an instance of windows running. Both of which seem flawed because it's still requiring a substantial amount of resources to load the entire os when only 1 tiny program is needed.

I do agree though that just running the program once every x hours might be a better solution than leaving the program or a container constantly running

**Comment by get-got** [comment]
I was messing around with it a bit last night but didn't do much. I'll try to get a docker build working tonight.

**Comment by get-got** [comment]
@nmills3 I **think** I properly set it up. I know nothing about Docker, but hopefully it works. Let me know.

https://hub.docker.com/repository/docker/getgot/discord-downloader-go

**Comment by nmills3** [comment]
1. i might be being a bit blind but i can't see how i'm meant to pass the config file to the docker container, do i need to mount a config file to the container?
2. the link you've used a docker link that only works if your signed into your profile, the public link is [https://hub.docker.com/r/getgot/discord-downloader-go](https://hub.docker.com/r/getgot/discord-downloader-go)

**Comment by nmills3** [comment]
Ok, i've managed to get a settings.json file loaded by mounting it to /root/settings.json but now whenever the container is run it just gets this error 

2021/01/24 10:49:06.412693 common.go:109: [Github Update Check] Error fetching current Release JSON: Get "https://api.github.com/repos/get-got/discord-downloader-go/releases/latest": x509: certificate signed by unknown authority

and then shortly after it gets this error and then quits out

2021/01/24 10:49:21.556365 main.go:219: Discord login failed: Get "https://discord.com/api/v6/gateway": x509: certificate signed by unknown authority

**Comment by get-got** [comment]
I've been playing around and pretty much got to where you are. I got the settings to mount fine but any web request seems to get the x509 error. Github, Discord, Twitter API; anything. I'm not sure how to fix that, I'll play around with it more tomorrow and see if I can find a solution. Let me know if you figure anything out.

**Comment by nmills3** [comment]
ok, also more of a QOL thing than anything else but i think on docker hub there is a way to add a list of settings that the container can have and their default values, it might be worth adding one for the config file because some things like unraid make use of that data and auto fill in fields, and it would give people some instruction on where to mount the settings file

**Comment by nmills3** [comment]
i'm no docker expert but this might help [https://medium.com/the-go-journey/x509-certificate-signed-by-unknown-authority-running-a-go-app-inside-a-docker-container-a12869337eb](https://medium.com/the-go-journey/x509-certificate-signed-by-unknown-authority-running-a-go-app-inside-a-docker-container-a12869337eb) i'd have a go myself but unfortunately I have no expierence with GO

**Comment by get-got** [comment]
@nmills3 I'll see if I can get it working tonight. @blay09 seems to have a custom Docker image working fine using Alpine so maybe it's a Scratch-specific issue. I know next to nothing about Docker but would like to get it working properly if possible, for others to use.

**Comment by blay09** [comment]
Yeah, I basically just replaced scratch with alpine as the base image. Alpine is still lightweight but comes with some useful basics, like the certificate store that's required to make https requests, and is more easily extendable since you can use apk/sh to further customize the image if you derive from it.

**Comment by nmills3** [comment]
I've managed to get a working docker build, i'm not sure how efficient it is but it is running. i've used this as my docker file

```
FROM golang:alpine AS builder

WORKDIR /app
RUN apk update && apk upgrade && apk add --no-cache ca-certificates
RUN update-ca-certificates

COPY . /go/src/github.com/github.com/get-got/discord-downloader-go
WORKDIR /go/src/github.com/github.com/get-got/discord-downloader-go

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o app .

FROM scratch
WORKDIR /root/
COPY --from=builder /go/src/github.com/github.com/get-got/discord-downloader-go/app .
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ENTRYPOINT ["./app"]
```

I found the info for the fix here [https://gist.github.com/michaelboke/564bf96f7331f35f1716b59984befc50](https://gist.github.com/michaelboke/564bf96f7331f35f1716b59984befc50) i'm sure someone else here can do a better job of building the image than i did

**Comment by nmills3** [comment]
Just realised you probably want to add a path variable to the docker hub so idiots like me remember to set a path for the downloader to save into instead of it saving back into it's own container. don't ask why i just thought of that, mistakes were made

**Comment by get-got** [comment]
I improved the Dockerfile: https://github.com/get-got/discord-downloader-go/commit/ee638e8f92b14971ed2a285392f57c04c8dffc61

Not sure how to properly setup environment variables for download location root & settings/database files (in a user-friendly manner at least, without just mounting volumes via command), I'll look into that tomorrow when I have time.

**Comment by nmills3** [comment]
from what i've seen other projects do, the most common option is to just mount a directory. so for your downloader i'd probably mount a volume to /SaveLocation/ and to /mnt/user/DiscordImageBackups/ImageBackups/ and then in the config i'd set the destination in the config to /SaveLocation/

**Comment by nmills3** [comment]
For the DB you're probably best just having another entry in the options to set the DB path. then people like me can just set docker the mount that path wherever we need it

**Comment by nmills3** [comment]
I can also confirm that the current docker build is running perfectly on docker in unraid using that new image you pushed
