### ISSUE TITLE
Getting <Username> tried using history command but history is already running for <Category ID>.

### ISSUE THREAD

**Issue by ExtremeMemes** [get-got/discord-downloader-go#91]
Im getting this error: `<Username> tried using history command but history is already running for <Category ID>.`

here is all the config file 

Note that sensitive information, like email has been changed
```
{
  "credentials": {
    "email": "email",
    "password": "pass"
  },
  "admins": [
    "MYID"
  ],
  "adminChannels": [
    {
      "channel": "CHANNEL"
    }
  ],
  "save": true,
  "allowCommands": false,
  "scanEdits": true,
  "ignoreBots": false,
  "messageOutput": false,    
  "sendErrorMessages": false,
  "presenceEnabled": false,
  "presenceStatus": "invisible",
  "reactWhenDownloaded": false,
  "reactWhenDownloadedHistory": false,
  "divideByChannel": true,
  "historyTyping": false,
   "autoHistory": false,
    "sendAutoHistoryStatus": true,

     "servers": [
        {
            "server": "",
            "destination": "hithisisthedir",
			 "divideByChannel": true
        }
    ],

  "categories": [
    {
	  "categories": [ "ID1", "ID2"],
      "destination": "files/cat1",
	  "autoHistory": false,
	  "sendAutoHistoryStatus": true
    }
  ]
}
```

**Comment by ExtremeMemes** [comment]
I ran `ddg history list` and got 

CURRENT HISTORY JOBS ~ 1 total, 1 running
• Currently Downloading... (My Username) My Own Server- Text Channels / #downloader, updated 38s ago, added 38s ago

#downloader being the admin channel for this application

**Comment by get-got** [comment]
> I ran `ddg history list` and got
> 
> CURRENT HISTORY JOBS ~ 1 total, 1 running • Currently Downloading... (My Username) My Own Server- Text Channels / #downloader, updated 38s ago, added 38s ago
> 
> #downloader being the admin channel for this application

@ExtremeMemes Try removing these 2 sets of lines, those are the default values so unless you're making autoHistory true you don't need them. That's all I'm seeing that I think could be causing that, though using those values shouldn't be causing your error, but if it is I'll fix it.

**Comment by ExtremeMemes** [comment]
i removed those lines, but it seems to be a problem with the category downloads.
