### ISSUE TITLE
Exceeded Since Date Filter

### ISSUE THREAD

**Issue by FLOOGETTA987** [get-got/discord-downloader-go#92]
I run the application and type in the command ddg history 1061781360009818243 --since=2023-03-30, then i get:

>Command — History
>
>1 second: 0 total files downloaded! 0 B total, avg 0.0 MB/s
>0 total messages processed
>
>Server: *********
>Category: *********
>Channel: #********
>
>DONE! - COMPLETE: Exceeded Since Date Filter
>Ran 0 message history requests
>
>Since: 1090862972928000000
>
>
>Duration was 1 second 986 milliseconds 847 microseconds

And afterwards there isnt anything in the folder, could someone tell me what i am doing wrong?

**Comment by get-got** [comment]
@FLOOGETTA987 Delete the cache folder and try it again. I'll be reworking how history caching works soon to fix issues like this.

**Comment by get-got** [comment]
Should be fixed as of v2.0.1
