### ISSUE TITLE
Blacklist a specific user 

### ISSUE THREAD

**Issue by NimbusCloudVoid** [get-got/discord-downloader-go#94]
Hello,
I wanted to know if it's possible to blacklist a specific user? I don't want to download their stuff and i wanted to know if it was possible? Is the "allBlacklistUsers" made for that or something else?

Thanks

**Comment by get-got** [comment]
@NimbusCloudVoid The following can be applied globally or per-source.

All are optional and will default to the below, just include `"blockedUsers": [ "123" ]` within a `filters` group like below.

![image](https://github.com/get-got/discord-downloader-go/assets/43052079/26a9e216-fe5e-4d3d-b5cd-291c0fbbae7d)

**Comment by NimbusCloudVoid** [comment]
Yeah i skipped it for some reason, that's on me my bad.
PS: i know some of the people who made issue are talking you like shit for a free project and it sucks but no need to do the same lol that won't help you in the future, especially here, other had worse than you but don't act like you do now lol. I missed one line while it was late my bad but thanks anyway

**Comment by get-got** [comment]
> Yeah i skipped it for some reason, that's on me my bad.
> 
> 
> 
> PS: i know some of the people who made issue here are talking to you like shit for a free project and it sucks but no need to do the same lol that won't help you in the future, especially here, other had worse than you but don't act like you do now lol. I missed one line while it was late my bad but thanks anyway 

See other reply. You had a fair question, I had absolutely no problem with this. The issue I posted was partially because of this, because I need to improve the readme to make it easier to find and understand settings like these.

**Comment by NimbusCloudVoid** [comment]
> > Yeah i skipped it for some reason, that's on me my bad.
> > PS: i know some of the people who made issue here are talking to you like shit for a free project and it sucks but no need to do the same lol that won't help you in the future, especially here, other had worse than you but don't act like you do now lol. I missed one line while it was late my bad but thanks anyway
> 
> See other reply. You had a fair question, I had absolutely no problem with this. The issue I posted was partially because of this, because I need to improve the readme to make it easier to find and understand settings like these.

Ah ok got it, didn't wanted to cause any problem for future people because of me
