### ISSUE TITLE
About URLs and Categories

### ISSUE THREAD

**Issue by NimbusCloudVoid** [get-got/discord-downloader-go#97]
Hello,
I wanted to know, does the script take into consideration the URLs from other websites and tries to download it? If not is it possible to sort of take those URLs and putting them into a txt files?
And for Categories, i tried to download a category because all the channels in it, i want to download it but when i try `ddg history (Category ID)` it doesn't works. Is it supported or not?

Thanks

**Comment by get-got** [comment]
@NimbusCloudVoid For categories you need to use "category" or "categories" in place of "channel" or "channels" in the settings.

If you're asking if the bot downloads from sources other than just Discord, yes, it'll download any direct files and attempt to fetch from particular sources like Instagram if you have the login setup for it.

**Comment by NimbusCloudVoid** [comment]
So if i let the lines channel/channels in the config and that i have the lines Category/categories in it, it won't work? Because i have those lines in the config but i put nothing in it except for category and it wouldn't work. I will try again with only category and comeback to you.

Thanks
